/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paedeias.vistas;

import com.paedeias.controladores.CGlobalConfig;
import com.paedeias.helpers.hPartidasReservaciones;
import com.paedeias.identidades.PartidasEnReservacion;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALL
 */
public class CatalogoArticulosReservaciones extends javax.swing.JPanel {

    /**
     * Creates new form CatalogoArticulosReservaciones
     */
    public CatalogoArticulosReservaciones() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Gran Total:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("0000.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel dtm;
    Vector encabezado,vector;
    hPartidasReservaciones hpartidasreservaciones;
    List<PartidasEnReservacion> partidas;
    double granTotal=0;
    DecimalFormat df;
    
public void inicializar()
{
    df = new DecimalFormat("0.00");
    hpartidasreservaciones =new hPartidasReservaciones();
    partidas = new ArrayList<PartidasEnReservacion>();
    
    encabezado = new Vector<String>();
    
    encabezado.add("Código Articulo");
    encabezado.add("Descripción");
    encabezado.add("Reservación");
    encabezado.add("Cliente");
    encabezado.add("Fecha");
    encabezado.add("Precio de Venta");
    encabezado.add(CGlobalConfig.getCampor6());
    encabezado.add(CGlobalConfig.getCampor8());
    encabezado.add(CGlobalConfig.getCampor13());

    partidas = hpartidasreservaciones.buscarPartidas();
    
    
    
    vector = new Vector();
    
    dtm = new DefaultTableModel(vector,encabezado){

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              };
    
             for(Object o: partidas){
             PartidasEnReservacion iarticulos = (PartidasEnReservacion)o;
             Vector<Object> unaFila = new Vector<Object>();
             granTotal = granTotal + Double.valueOf(iarticulos.getPrecioVenta());
             unaFila.add(iarticulos.getCodArt());
             unaFila.add(iarticulos.getDescripcion());
             unaFila.add(iarticulos.getIdRes());
             unaFila.add(iarticulos.getCliente());
             unaFila.add(iarticulos.getFecha());
             unaFila.add(iarticulos.getPrecioVenta());
             unaFila.add(iarticulos.getTipoAuto());
             unaFila.add(iarticulos.getModelo());
             unaFila.add(iarticulos.getVale());
             vector.add(unaFila);
             }
    jTable1.setModel(dtm);
    dtm.fireTableDataChanged();
    jLabel2.setText(df.format(granTotal));
}
}