/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FArticulos.java
 *
 * Created on 29/03/2012, 05:10:43 PM
 */

package com.paedeias.vistas;

import com.paedeias.controladores.CConfiguracion;
import com.paedeias.helpers.hArticulos;
import com.paedeias.helpers.hKardex;
import com.paedeias.identidades.Articulos;
import com.paedeias.identidades.Kardex;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Luis
 */
public class FAplicaciones extends javax.swing.JPanel {

    /** Creates new form FArticulos */
    public FAplicaciones() {
        initComponents();
        jButton3.setEnabled(CConfiguracion.isInventario());
        jButton6.setEnabled(CConfiguracion.isInventario());
        jButton2.setEnabled(CConfiguracion.isEtiquetas());
        jButton5.setEnabled(CConfiguracion.isEtiquetas());
        jButton7.setEnabled(CConfiguracion.isConfiguracion());
        jButton8.setEnabled(CConfiguracion.isConfiguracion());
        jButton9.setEnabled(CConfiguracion.isRegistrarKardex());
        jButton10.setEnabled(CConfiguracion.isRegistrarKardex());
        jButton11.setEnabled(CConfiguracion.isRespaldo());
        jButton12.setEnabled(CConfiguracion.isRespaldo());
        jButton13.setEnabled(CConfiguracion.isConfigurarPlugins());
        jButton14.setEnabled(CConfiguracion.isConfigurarPlugins());
 /*        if(CConfiguracion.getPuesto().equals("Reservaciones"))
        {
            jButton2.setEnabled(false);
            jButton5.setEnabled(false);
        }
         if(CConfiguracion.getPuesto().equals("Administración"))
        {
            jButton3.setEnabled(true);
            jButton6.setEnabled(true);            
        } */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/inventario.jpg"))); // NOI18N
        jButton3.setToolTipText("Inventario");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/star.jpg"))); // NOI18N
        jButton9.setToolTipText("Inventario");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/safebox.jpg"))); // NOI18N
        jButton11.setToolTipText("Respaldo");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(29, 29, 29)
                .addComponent(jButton9)
                .addGap(31, 31, 31)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton6.setBackground(new java.awt.Color(11, 70, 119));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Inventario");
        jButton6.setToolTipText("Inventario");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(11, 70, 119));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Registrar Kardex");
        jButton10.setToolTipText("Inventario");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setOpaque(true);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(11, 70, 119));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Respaldo");
        jButton12.setToolTipText("Respaldo");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setOpaque(true);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/tag.png"))); // NOI18N
        jButton2.setToolTipText("Etiquetas");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/configuracion.jpg"))); // NOI18N
        jButton7.setToolTipText("Configuración");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/pluginConf.jpg"))); // NOI18N
        jButton13.setToolTipText("Configuración de Plugins");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setBackground(new java.awt.Color(11, 70, 119));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Etiquetas");
        jButton5.setToolTipText("Etiquetas");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(11, 70, 119));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Configuración");
        jButton8.setToolTipText("Configuración");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(11, 70, 119));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Configuración de Plugins");
        jButton14.setToolTipText("Configuración de Plugins");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setOpaque(true);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            VImpresionEtiquetas vietq = new VImpresionEtiquetas();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Impresión de Etiquetas",indice));  
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            VImpresionEtiquetas vietq = new VImpresionEtiquetas();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Impresión de Etiquetas",indice));    
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // TODO add your handling code here:
            VRealizar_Inventario vietq = new VRealizar_Inventario();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Inventario",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                // TODO add your handling code here:
            VRealizar_Inventario vietq = new VRealizar_Inventario();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Inventario",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            // TODO add your handling code here:
            VConfiguracion vietq = new VConfiguracion();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Configuración",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           // TODO add your handling code here:
            VConfiguracion vietq = new VConfiguracion();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Configuración",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    JPanel panel = new JPanel();
    JLabel label = new JLabel("Ingresa la contraseña:");
    JPasswordField pass = new JPasswordField(10);
    panel.add(label);
    panel.add(pass);
    String[] options = new String[]{"OK", "Cancelar"};
    int option = JOptionPane.showOptionDialog(null, panel, "Proceso en Kardex",
                         JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                         null, options, options[1]);
    if(option == JOptionPane.YES_OPTION) // pressing OK button
       {
    char[] password = pass.getPassword();
    String contrasena = new String(password);
   // System.out.println("Your password is: " + new String(password));
    
    if(contrasena.equals("albaca"))
    {
        System.out.println("Iniciando proceso de Actualización");
        hKardex hkardex = new hKardex();
        hkardex.truncarKardex();
        hArticulos harticulos = new hArticulos();
        List<Articulos> articulos = harticulos.consultaArticulos("", "*", "");
        Kardex kardex = new Kardex();
        
        for(int i=0; i<articulos.size(); i++)
        {
        kardex.setAlmacenista("Sin Almacenista");    
        kardex.setArticulo(articulos.get(i).getCodigo());
        kardex.setAnticipos(articulos.get(i).getAnticipos()); // 
        kardex.setEntrada(0);
        kardex.setExistencias((int)articulos.get(i).getExistencia());
        kardex.setIdArticulo(articulos.get(i).getId());
        kardex.setModificacion("Registro de Artículo");
        kardex.setMovimiento("Registro de Artículo");
        kardex.setNoMov("1");
        kardex.setPrecioVenta(articulos.get(i).getPrecioVenta());
        kardex.setRefFerrari("Registro");
        kardex.setReservados((int)articulos.get(i).getReservado());
        kardex.setResponsable("1");
        kardex.setResponsable2("LUIS LAREDO"); //
        kardex.setSalida(0);
        kardex.setUltimoCosto(articulos.get(i).getPrecioCompra());
        kardex.setVendidoEn(0.00);
        hkardex.guardarEnKardex(kardex);
        }
        
        
        JOptionPane.showMessageDialog(null, "Proceso completado");
    }else
    {
        JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
        return;
    }
    
    
       }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
            VRealizar_Respaldo vietq = new VRealizar_Respaldo();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Respaldo",indice));    
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
            VRealizar_Respaldo vietq = new VRealizar_Respaldo();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vietq), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Respaldo",indice));    
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

            VCatalogo_Plugins vplug = new VCatalogo_Plugins();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vplug), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Configuración de Plugins",indice));    
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

            VCatalogo_Plugins vplug = new VCatalogo_Plugins();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vplug), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Configuración de Plugins",indice));    
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
    }//GEN-LAST:event_jButton14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
