/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FProveedores.java
 *
 * Created on 29/03/2012, 06:29:46 PM
 */

package com.paedeias.vistas;

import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Luis
 */
public class FProveedores extends javax.swing.JPanel {

    /** Creates new form FProveedores */
    public FProveedores() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/BvanIcon.jpg"))); // NOI18N
        jButton1.setToolTipText("Catálogo de proveedores");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton2.setText("Proveedores");
        jButton2.setToolTipText("Catálogo de Proveedores");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          VCatalogo_Proveedores catprov = new VCatalogo_Proveedores();

          int indice = ((JTabbedPane)getParent()).getSelectedIndex();
              indice +=1;
             //        ((JTabbedPane)getParent()).insertTab("Actualiza",null, new JScrollPane(actualiza), "Actualiza Proveedores", indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(catprov), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de proveedores",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                  VCatalogo_Proveedores catprov = new VCatalogo_Proveedores();

          int indice = ((JTabbedPane)getParent()).getSelectedIndex();
              indice +=1;
             //        ((JTabbedPane)getParent()).insertTab("Actualiza",null, new JScrollPane(actualiza), "Actualiza Proveedores", indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(catprov), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de proveedores",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
