/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paedeias.vistas;

import com.paedeias.controladores.CConfiguracion;
import com.paedeias.controladores.Numero_a_Letra;
import com.paedeias.controladores.Validadores;
import com.paedeias.helpers.hAnticipos;
import com.paedeias.identidades.Anticipos;
import com.paedeias.identidades.Factura;
import com.paedeias.identidades.Partidas;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author ALL
 */
public class PAnticipos extends javax.swing.JPanel {

    /**
     * Creates new form PAnticipos
     */
    public PAnticipos() { 
        initComponents(); 
        
        jButton1.setEnabled(CConfiguracion.isRealizarAnticipos());
        jButton2.setEnabled(CConfiguracion.isRealizarAnticipos());
        jButton5.setEnabled(CConfiguracion.isVentasAnticipos());
        jButton6.setEnabled(CConfiguracion.isVentasAnticipos());
        jButton3.setEnabled(CConfiguracion.isCatalogoAnticipos());
        jButton4.setEnabled(CConfiguracion.isCatalogoAnticipos());
        jButton7.setEnabled(CConfiguracion.isArticulosAnticipos());
        jButton8.setEnabled(CConfiguracion.isArticulosAnticipos());
        jButton9.setEnabled(CConfiguracion.isFacturasparciales());
        jButton10.setEnabled(CConfiguracion.isFacturasparciales());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/anticipos.jpg"))); // NOI18N
        jButton1.setToolTipText("Realizar Anticipos");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/CatVentasAnticipos.jpg"))); // NOI18N
        jButton5.setToolTipText("Catálogo de las Ventas con Anticipos");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/Catcompras.jpg"))); // NOI18N
        jButton9.setToolTipText("Facturas para pagos parciales");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(11, 70, 119));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Realizar Anticipos");
        jButton2.setToolTipText("Realizar Anticipos");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(11, 70, 119));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Catálogo Ventas Anticipos");
        jButton6.setToolTipText("Catálogo de las Ventas con Anticipos");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(11, 70, 119));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Factura de Pago Parcial");
        jButton10.setToolTipText("Facturas para pagos parciales");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setOpaque(true);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/catAnticipos.jpg"))); // NOI18N
        jButton3.setToolTipText("Catálogo de Anticipos");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/itemAnticipos.jpg"))); // NOI18N
        jButton7.setToolTipText("Catálogo de Articulos en Anticipos");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(20, 20, 20)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(11, 70, 119));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Catálogo de Anticipos");
        jButton4.setToolTipText("Catálogo de Anticipos");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(11, 70, 119));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Artículos en Anticipos");
        jButton8.setToolTipText("Catálogo de Artículso en Anticipos");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
            VRealizarAnticipo vrealizaanticipo = new VRealizarAnticipo();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vrealizaanticipo), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
            VRealizarAnticipo vrealizaanticipo = new VRealizarAnticipo();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vrealizaanticipo), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            VCatalogo_Anticipos vcatanticipos = new VCatalogo_Anticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            VCatalogo_Anticipos vcatanticipos = new VCatalogo_Anticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            VCatalogoVenta_Anticipos vcatanticipos = new VCatalogoVenta_Anticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo Venta Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            VCatalogoVenta_Anticipos vcatanticipos = new VCatalogoVenta_Anticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo Venta Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            // TODO add your handling code here:
            CatalogoArticulosAnticipos vcatanticipos = new CatalogoArticulosAnticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Artículos en Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            CatalogoArticulosAnticipos vcatanticipos = new CatalogoArticulosAnticipos();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vcatanticipos), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Artículos en Anticipos",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        hAnticipos hanticipos = new hAnticipos();
        
        String monto = JOptionPane.showInputDialog(null,"Por favor captura el monto que deseas capturar");
        String referencia = JOptionPane.showInputDialog(null,"Por favor escribe la referencia del pago parcial");
        
        if (monto == null || referencia == null)
            return;
        
        if(!Validadores.validarDoble("Monto", monto))
            return;       
        
        List<Anticipos> validadorAnt = hanticipos.consultaAnticipos("referencia", "=", String.valueOf(referencia));
        
        if(!validadorAnt.isEmpty())
         {
        if(validadorAnt.get(0).getCancelado() == 1)
        {
            JOptionPane.showMessageDialog(null, "Este anticipo ya ha sido cancelado");
            return;
        }
        if(validadorAnt.get(0).getTicket() == 1 || validadorAnt.get(0).getFactura() == 1)
        {
            JOptionPane.showMessageDialog(null, "Este anticipo ya ha sido vendido");
            return;
        }
         }                       
        //caso público en general      
        double fsubtotal = Double.valueOf(monto);
        double ftotal = Double.valueOf(monto);
        double fiva = 0;


        
        Numero_a_Letra numeroaletra = new Numero_a_Letra();
        Factura ventafactura = new Factura();
        
        ventafactura.setFormaDePago("Efectivo");
        ventafactura.setSubtotal(String.valueOf(df.format(fsubtotal)));
        ventafactura.setImpuesto(String.valueOf(df.format(fiva)));
        ventafactura.setTotal(String.valueOf(df.format(ftotal)));
        ventafactura.setIdConceptoFactura("ANTP"+referencia);
        ventafactura.setTotalLetra(numeroaletra.Convertir(df.format(ftotal), true));
        ventafactura.setIdReceptorF(1);
        // ventafactura.setMotivo(jTextField2.getText());
        ventafactura.setMotivo("Anticipo "+referencia);
        // ventafactura.setMotivo(String.valueOf(venta.getId()));
        ventafactura.setMovimiento("Efectivo");
        
        
        List<Partidas> partidasfacturas = new ArrayList<Partidas>();
        Partidas partidafactura = new Partidas();
        partidafactura.setBeneficio(ftotal);
        partidafactura.setCantidad(1);
        partidafactura.setClasificacion("");
        partidafactura.setCodigoArticulo("0000");
        partidafactura.setConBeneficio(ftotal);
        partidafactura.setDescripcionArticulo("PAGO PARCIAL DEL ANTICIPO " +referencia);
        partidafactura.setExistenciaAlmacen(0);
        partidafactura.setIdArticulo((long)0);
        partidafactura.setIdCompleto("");
        partidafactura.setIdVenta((long)0);
        partidafactura.setPrecioCompra(0.00);
        partidafactura.setPrecioVenta(ftotal);
        partidafactura.setSubtotal(ftotal);
        partidafactura.setTipoBeneficio("");
        partidafactura.setUbicacion("");
        partidasfacturas.add(partidafactura);
        
        VDetalle_FacturaCFDIAnticipo factura = new VDetalle_FacturaCFDIAnticipo(ventafactura,"parcial",partidasfacturas);
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(factura), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Factura", indice));
        ((JTabbedPane) getParent()).setSelectedIndex(indice);     
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        hAnticipos hanticipos = new hAnticipos();
        
        String monto = JOptionPane.showInputDialog(null,"Por favor captura el monto que deseas capturar");
        String referencia = JOptionPane.showInputDialog(null,"Por favor escribe la referencia del pago parcial");
                
        if (monto == null || referencia == null)
        return;
        
        if(!Validadores.validarDoble("Monto", monto))
        return;      
        
           List<Anticipos> validadorAnt = hanticipos.consultaAnticipos("referencia", "=", String.valueOf(referencia));
        
           
         if(!validadorAnt.isEmpty())
         {
        if(validadorAnt.get(0).getCancelado() == 1)
        {
            JOptionPane.showMessageDialog(null, "Este anticipo ya ha sido cancelado");
            return;
        }
        if(validadorAnt.get(0).getTicket() == 1 || validadorAnt.get(0).getFactura() == 1)
        {
            JOptionPane.showMessageDialog(null, "Este anticipo ya ha sido vendido");
            return;
        }
         }
                                
        //caso público en general      
        double fsubtotal = Double.valueOf(monto);
        double ftotal = Double.valueOf(monto);
        double fiva = 0;


        
        Numero_a_Letra numeroaletra = new Numero_a_Letra();
        Factura ventafactura = new Factura();
        
        ventafactura.setFormaDePago("Efectivo");
        ventafactura.setSubtotal(String.valueOf(df.format(fsubtotal)));
        ventafactura.setImpuesto(String.valueOf(df.format(fiva)));
        ventafactura.setTotal(String.valueOf(df.format(ftotal)));
        ventafactura.setIdConceptoFactura("ANTP"+referencia);
        ventafactura.setTotalLetra(numeroaletra.Convertir(df.format(ftotal), true));
        ventafactura.setIdReceptorF(1);
        // ventafactura.setMotivo(jTextField2.getText());
        ventafactura.setMotivo("Anticipo "+referencia);
        // ventafactura.setMotivo(String.valueOf(venta.getId()));
        ventafactura.setMovimiento("Efectivo");
        
       
        List<Partidas> partidasfacturas = new ArrayList<Partidas>();
        Partidas partidafactura = new Partidas();
        partidafactura.setBeneficio(ftotal);
        partidafactura.setCantidad(1);
        partidafactura.setClasificacion("");
        partidafactura.setCodigoArticulo("0000");
        partidafactura.setConBeneficio(ftotal);
        partidafactura.setDescripcionArticulo("PAGO PARCIAL DEL ANTICIPO " +referencia);
        partidafactura.setExistenciaAlmacen(0);
        partidafactura.setIdArticulo((long)0);
        partidafactura.setIdCompleto("");
        partidafactura.setIdVenta(Long.valueOf(referencia));
        partidafactura.setPrecioCompra(0.00);
        partidafactura.setPrecioVenta(ftotal);
        partidafactura.setSubtotal(ftotal);
        partidafactura.setTipoBeneficio("");
        partidafactura.setUbicacion("");
        partidasfacturas.add(partidafactura);
        
        VDetalle_FacturaCFDIAnticipo factura = new VDetalle_FacturaCFDIAnticipo(ventafactura,"parcial",partidasfacturas);
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(factura), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Factura", indice));
        ((JTabbedPane) getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
