/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FArticulos.java
 *
 * Created on 29/03/2012, 05:10:43 PM
 */

package com.paedeias.vistas;

import com.paedeias.controladores.CConfiguracion;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Luis
 */
public class PVentas extends javax.swing.JPanel {

    /** Creates new form FArticulos */
    public PVentas() {
        initComponents();
        jButton1.setEnabled(CConfiguracion.isRealizarVenta());
        jButton4.setEnabled(CConfiguracion.isRealizarVenta());
        jButton2.setEnabled(CConfiguracion.isCatalogoVentas());
        jButton5.setEnabled(CConfiguracion.isCatalogoVentas());
        jButton12.setEnabled(CConfiguracion.isCatalogoFacturas());
        jButton13.setEnabled(CConfiguracion.isCatalogoFacturas());
        jButton7.setEnabled(CConfiguracion.isKardex());
        jButton8.setEnabled(CConfiguracion.isKardex());
        jButton9.setEnabled(CConfiguracion.isCatalogoDevoluciones());
        jButton6.setEnabled(CConfiguracion.isCatalogoDevoluciones());
        jButton10.setEnabled(CConfiguracion.isAlmacenDevoluciones());
        jButton11.setEnabled(CConfiguracion.isAlmacenDevoluciones());
        jButton16.setEnabled(CConfiguracion.isCierres());
        jButton17.setEnabled(CConfiguracion.isCierres());
        jButton18.setEnabled(CConfiguracion.isOfertas());
        jButton19.setEnabled(CConfiguracion.isOfertas());
        jButton3.setEnabled(CConfiguracion.isReservaciones());
        jButton14.setEnabled(CConfiguracion.isReservaciones());
        jButton20.setEnabled(CConfiguracion.isArticulosReservaciones());
        jButton21.setEnabled(CConfiguracion.isArticulosReservaciones());
      /*    if(CConfiguracion.getPuesto().equals("Ventas"))
        {
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton9.setEnabled(false);
            jButton6.setEnabled(false);
            jButton16.setEnabled(false);
            jButton11.setEnabled(false);
            jButton10.setEnabled(false);
            jButton17.setEnabled(false);
        }else if(CConfiguracion.getPuesto().equals("Almacén"))
        {
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton9.setEnabled(false);
            jButton6.setEnabled(false);
            jButton16.setEnabled(false);
            jButton17.setEnabled(false);
            jButton11.setEnabled(false);
            jButton10.setEnabled(false);
        }else if(CConfiguracion.getPuesto().equals("Reservaciones"))
        {
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
            jButton5.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton9.setEnabled(false);
            jButton6.setEnabled(false);
            jButton16.setEnabled(false);
            jButton17.setEnabled(false);
            jButton11.setEnabled(false);
            jButton10.setEnabled(false);
        } */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/ventas.jpg"))); // NOI18N
        jButton1.setToolTipText("Ventas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/catVentas.jpg"))); // NOI18N
        jButton2.setToolTipText("Catálogo de Ventas");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/factura.jpg"))); // NOI18N
        jButton12.setToolTipText("Catálogo de Facturas");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/door.png"))); // NOI18N
        jButton16.setToolTipText("Cierres");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setOpaque(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/CatReservaciones.jpg"))); // NOI18N
        jButton3.setToolTipText("Catálogo de Reservaciones");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(11, 70, 119));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Realizar Ventas");
        jButton4.setToolTipText("Ventas");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(11, 70, 119));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Catálogo de Ventas");
        jButton5.setToolTipText("Catálogo de Ventas");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(11, 70, 119));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Catálogo de Facturas");
        jButton13.setToolTipText("Catálogo de Facturas");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setOpaque(true);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(11, 70, 119));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Cierres");
        jButton17.setToolTipText("Cierres");
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setOpaque(true);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(11, 70, 119));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("Catálogo de Reservaciones");
        jButton14.setToolTipText("Catálogo de Reservaciones");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setOpaque(true);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/kardexDoc.jpg"))); // NOI18N
        jButton7.setToolTipText("Kardex");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/devoluciones.jpg"))); // NOI18N
        jButton9.setToolTipText("Catálogo de Devoluciones");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/adevoluciones.jpg"))); // NOI18N
        jButton10.setToolTipText("Catálogo de Facturas");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/descuento.jpg"))); // NOI18N
        jButton18.setToolTipText("Ofertas");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setOpaque(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/itemReservaciones.jpg"))); // NOI18N
        jButton20.setToolTipText("Artículos de Reservacioness");
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setOpaque(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton18)
                    .addComponent(jButton20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton8.setBackground(new java.awt.Color(11, 70, 119));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Kardex");
        jButton8.setToolTipText("Kardex");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(11, 70, 119));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Catálogo de Devoluciones");
        jButton6.setToolTipText("Catálogo de Devoluciones");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(11, 70, 119));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Almacén de Devoluciones");
        jButton11.setToolTipText("Catálogo de Devoluciones");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setOpaque(true);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(11, 70, 119));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("Ofertas");
        jButton19.setToolTipText("Ofertas");
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setOpaque(true);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(11, 70, 119));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Artículos de Reservaciones");
        jButton21.setToolTipText("Artículos de Reservaciones");
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setOpaque(true);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            VRealizar_Venta vrealizarventa = new VRealizar_Venta();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Venta",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          VCat_Kardex catalogokardex = new VCat_Kardex();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(new JScrollPane(catalogokardex), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Kardex",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            VCat_Kardex catalogokardex = new VCat_Kardex();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(new JScrollPane(catalogokardex), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Kardex",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        VCatalogo_Ventas catalogoventas = new VCatalogo_Ventas();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogoventas), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Ventas", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VCatalogo_Ventas catalogoventas = new VCatalogo_Ventas();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogoventas), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Ventas", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         VCatalogo_Devoluciones catalogodevoluciones = new VCatalogo_Devoluciones();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogodevoluciones), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Devoluciones", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         VCatalogo_Devoluciones catalogodevoluciones = new VCatalogo_Devoluciones();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogodevoluciones), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Devoluciones", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        VCatalogo_AlmacenDevoluciones catalogoadevoluciones = new VCatalogo_AlmacenDevoluciones();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogoadevoluciones), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Almacén de Devoluciones", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        VCatalogo_AlmacenDevoluciones catalogoadevoluciones = new VCatalogo_AlmacenDevoluciones();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogoadevoluciones), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Almacén de Devoluciones", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         // TODO add your handling code here:
        VCatalogo_Facturas catalogofacturas = new VCatalogo_Facturas();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogofacturas), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Facturas", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
                // TODO add your handling code here:
        VCatalogo_Facturas catalogofacturas = new VCatalogo_Facturas();
        int indice = ((JTabbedPane) getParent()).getSelectedIndex();
        indice += 1;
        ((JTabbedPane) getParent()).add(new JScrollPane(catalogofacturas), indice);
        ((JTabbedPane) getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Facturas", indice));
        ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
            // TODO add your handling code here:
            VCatalogoCierres cierre = new VCatalogoCierres();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(cierre, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Cierre",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
            // TODO add your handling code here:
            VCatalogoCierres cierre = new VCatalogoCierres();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(cierre, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Cierre",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
            
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
            // TODO add your handling code here:
            VRealizarOferta cierre = new VRealizarOferta();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(cierre), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Crear Oferta",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
            // TODO add your handling code here:
            VRealizarOferta cierre = new VRealizarOferta();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(cierre), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Crear Oferta",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            VRealizar_Venta vrealizarventa = new VRealizar_Venta();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            //((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).add(new JScrollPane(vrealizarventa), indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Realizar Venta",indice));  
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            VCatalogo_Reservaciones vcatalogoreservaciones = new VCatalogo_Reservaciones();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(vcatalogoreservaciones, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Reservaciones",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        
            VCatalogo_Reservaciones vcatalogoreservaciones = new VCatalogo_Reservaciones();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(vcatalogoreservaciones, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Catálogo de Reservaciones",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
            CatalogoArticulosReservaciones vcatalogoreservaciones = new CatalogoArticulosReservaciones();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(vcatalogoreservaciones, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Artículos de Reservaciones",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice); 
        
        
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
            CatalogoArticulosReservaciones vcatalogoreservaciones = new CatalogoArticulosReservaciones();
            int indice = ((JTabbedPane)getParent()).getSelectedIndex();
            indice +=1;
            ((JTabbedPane)getParent()).add(vcatalogoreservaciones, indice);
            ((JTabbedPane)getParent()).setTabComponentAt(indice, new botonCierre("Artículos de Reservaciones",indice));
            ((JTabbedPane)getParent()).setSelectedIndex(indice);
        
        
        
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

}
