/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paedeias.vistas;

import com.paedeias.controladores.CGlobalConfig;
import com.paedeias.helpers.*;
import com.paedeias.identidades.ReporteComisiones;
import com.paedeias.identidades.ReporteUtilidades;
import com.paedeias.identidades.Usuarios;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ALL
 */
public class V_ReporteComisiones extends javax.swing.JPanel {

    /**
     * Creates new form V_ReporteComisiones
     */
    public V_ReporteComisiones() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo4 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("De");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("a");

        jButton1.setBackground(new java.awt.Color(11, 70, 119));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generar");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Usando Devoluciones del periodo");

        jLabel3.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooserCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1)
                    .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dateChooserCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("0000.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Total en Ventas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    
                  //------------- CAMBIO DE FORMATO -----------------
                     
                     final String OLD_FORMAT = "dd/MM/yy";
                     final String NEW_FORMAT = "yyyy/MM/dd";

                     // August 12, 2010
                     String oldDateString = dateChooserCombo1.getText();
                     String newDateString;

                     SimpleDateFormat sdf = new SimpleDateFormat(OLD_FORMAT);
                     Date d = null;
                      try {
                     d = sdf.parse(oldDateString);
                     } catch (ParseException ex) {
                     Logger.getLogger(V_ReporteComisiones.class.getName()).log(Level.SEVERE, null, ex);
                      }
                     sdf.applyPattern(NEW_FORMAT);
                     newDateString = sdf.format(d);
                     newDateString = newDateString + " 00:00:00";
                     
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                     final String OLD_FORMAT2 = "dd/MM/yy";
                     final String NEW_FORMAT2 = "yyyy/MM/dd";

                     // August 12, 2010
                     String oldDateString2 = dateChooserCombo2.getText();
                     String newDateString2;

                     SimpleDateFormat sdf2 = new SimpleDateFormat(OLD_FORMAT2);
                     Date d2 = null;
                      try {
                     d2 = sdf2.parse(oldDateString2);
                     } catch (ParseException ex) {
                     Logger.getLogger(V_ReporteComisiones.class.getName()).log(Level.SEVERE, null, ex);
                      }
                     sdf2.applyPattern(NEW_FORMAT2);
                     newDateString2 = sdf.format(d2);
                     newDateString2 = newDateString2 + " 23:59:59";
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                     final String OLD_FORMAT3 = "dd/MM/yy";
                     final String NEW_FORMAT3 = "yyyy/MM/dd";

                     // August 12, 2010
                     String oldDateString3 = dateChooserCombo3.getText();
                     String newDateString3;

                     SimpleDateFormat sdf3 = new SimpleDateFormat(OLD_FORMAT3);
                     Date d3 = null;
                      try {
                     d3 = sdf3.parse(oldDateString3);
                     } catch (ParseException ex) {
                     Logger.getLogger(V_ReporteComisiones.class.getName()).log(Level.SEVERE, null, ex);
                      }
                     sdf3.applyPattern(NEW_FORMAT3);
                     newDateString3 = sdf.format(d3);
                     newDateString3 = newDateString3 + " 00:00:00";
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                    //------------- CAMBIO DE FORMATO -----------------
                     
                     final String OLD_FORMAT4 = "dd/MM/yy";
                     final String NEW_FORMAT4 = "yyyy/MM/dd";

                     // August 12, 2010
                     String oldDateString4 = dateChooserCombo4.getText();
                     String newDateString4;

                     SimpleDateFormat sdf4 = new SimpleDateFormat(OLD_FORMAT4);
                     Date d4 = null;
                      try {
                     d4 = sdf4.parse(oldDateString4);
                     } catch (ParseException ex) {
                     Logger.getLogger(V_ReporteComisiones.class.getName()).log(Level.SEVERE, null, ex);
                      }
                     sdf4.applyPattern(NEW_FORMAT4);
                     newDateString4 = sdf.format(d4);
                     newDateString4 = newDateString4 + " 23:59:59";
                     
                     //------------- CAMBIO DE FORMATO -----------------
                     
                     listaComisiones.clear();
                     int cantidad=0;
                     double importe=0;
                     int cantidadr=0;
                     double importer=0;
                     int cantidadan=0;
                     double importean=0;
                     int cantidadau=0;
                     double importeau=0;
                     int cantidadd=0;
                     double imported=0;
                     
                     vector.clear();
                     totalVentas = 0;
                     
                     for(int i=0; i<vendedores.size(); i++)
                     {
                     List<ReporteComisiones> rc = hventas.consultaVentasPeriodoVendendor(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));
                     cantidad = 0;
                     importe = 0;
                     for(int o=0; o<rc.size(); o++)
                     {
                         cantidad = cantidad + rc.get(o).getCantidad();
                         importe = importe + rc.get(o).getImporte();
                     }
                     List<ReporteComisiones> rcr = hventas.consultaVentasPeriodoVendendorReservacion(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));
                     cantidadr = 0;
                     importer = 0;
                     for(int o=0; o<rcr.size(); o++)
                     {
                         cantidadr = cantidadr + rcr.get(o).getCantidadR();
                         importer = importer + rcr.get(o).getImporteR();
                     }
                     List<ReporteComisiones> rcan = hventasanticipos.consultaVentasPeriodoVendendorN(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));
                     cantidadan = 0;
                     importean = 0;
                     for(int o=0; o<rcan.size(); o++)
                     {
                         cantidadan = cantidadan + rcan.get(o).getCantidadAN();
                         importean = importean + rcan.get(o).getImporteAN();
                     }
                     List<ReporteComisiones> rcau = hventasanticipos.consultaVentasPeriodoVendendorU(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));
                     cantidadau = 0;
                     importeau = 0;
                     for(int o=0; o<rcau.size(); o++)
                     {
                         cantidadau = cantidadau + rcau.get(o).getCantidadAU();
                         importeau = importeau + rcau.get(o).getImporteAU();
                     }
                     cantidadd = 0;
                     imported = 0;
                     
                     if(jCheckBox1.isSelected())
                     {
                     List<ReporteComisiones> rcd = hventas.consultaDevolucionesPeriodoVendendor(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));

                     for(int o=0; o<rcd.size(); o++)
                     {
                         cantidadd = cantidadd + rcd.get(o).getCantidadD();
                         imported = imported + rcd.get(o).getImporteD();
                     }                     
                      List<ReporteComisiones> rcda = hventasanticipos.consultaDevolucionesPeriodoVendendor(newDateString, newDateString2,String.valueOf(vendedores.get(i).getId()));
                     for(int o=0; o<rcda.size(); o++)
                     {
                         cantidadd = cantidadd + rcda.get(o).getCantidadD();
                         imported = imported + rcda.get(o).getImporteD();
                     }                     
                     }
                     ReporteComisiones orc = new ReporteComisiones();
                     orc.setCantidad(cantidad);
                     orc.setImporte(importe);
                     orc.setCantidadR(cantidadr);
                     orc.setImporteR(importer);
                     orc.setCantidadAN(cantidadan);
                     orc.setImporteAN(importean);
                     orc.setCantidadAU(cantidadau);
                     orc.setImporteAU(importeau);
                     orc.setCantidadD(cantidadd);
                     orc.setImporteD(imported);
                     orc.setTotalVentas(cantidad + cantidadr+cantidadan+cantidadau);
                     orc.setTotalImporte(importe + importer + importean+ importeau);
                     orc.setTotalImporteSIva(((orc.getTotalImporte() - importeau) / (1+CGlobalConfig.getIvaVenta())) + importeau);
                     orc.setComision(orc.getTotalImporteSIva() * vendedores.get(i).getComision()); 
                     orc.setTotalImporteNegSIva(imported/(1+CGlobalConfig.getIvaVenta()));
                     orc.setComisionNeg(orc.getTotalImporteNegSIva() * vendedores.get(i).getComision());
                     orc.setTotalNeto(orc.getComision() - orc.getComisionNeg());
                     orc.setIdVendedor(vendedores.get(i).getId());
                     orc.setNombreVendedor(vendedores.get(i).getNombres() + " "+vendedores.get(i).getApellidoP()+" "+vendedores.get(i).getApellidoM());
                     
                     
                     listaComisiones.add(orc);
                     
                     }
                       
                     
                   for(int a=0; a<listaComisiones.size(); a++)
                   {
                  Vector<Object> vec = new Vector();
                  vec.add(listaComisiones.get(a).getNombreVendedor());    
                  vec.add(listaComisiones.get(a).getCantidad());
                  vec.add(df.format(listaComisiones.get(a).getImporte()));
                  vec.add(listaComisiones.get(a).getCantidadR());
                  vec.add(df.format(listaComisiones.get(a).getImporteR()));
                  vec.add(listaComisiones.get(a).getCantidadAN());
                  vec.add(df.format(listaComisiones.get(a).getImporteAN()));
                  vec.add(listaComisiones.get(a).getCantidadAU());
                  vec.add(df.format(listaComisiones.get(a).getImporteAU()));
                  vec.add(listaComisiones.get(a).getTotalVentas());
                  vec.add(df.format(listaComisiones.get(a).getTotalImporte()));
                  vec.add(df.format(listaComisiones.get(a).getTotalImporteSIva()));
                  vec.add(df.format(listaComisiones.get(a).getComision()));
                  vec.add(listaComisiones.get(a).getCantidadD());
                  vec.add(df.format(listaComisiones.get(a).getImporteD()));
                  vec.add(df.format(listaComisiones.get(a).getTotalImporteNegSIva()));
                  vec.add(df.format(listaComisiones.get(a).getComisionNeg()));
                  vec.add(df.format(listaComisiones.get(a).getTotalNeto()));
                  totalVentas = totalVentas + listaComisiones.get(a).getTotalImporteSIva();
                  vector.add(vec);
                   }
                   
                   
                   
                  dtm.fireTableDataChanged();
                  
                  jLabel4.setText(df.format(totalVentas));
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private datechooser.beans.DateChooserCombo dateChooserCombo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    List<Usuarios> vendedores;
    hUsuarios husuarios;
    DecimalFormat df,df2;
    Vector vector, vectorEncabezado;
    DefaultTableModel dtm;
    hVentas hventas;
    hVentaAnticipos hventasanticipos;
    List<ReporteComisiones> listaComisiones;
    double totalVentas=0;
    
     public void inicializar()
    {
        husuarios = new hUsuarios();
        hventas = new hVentas();
        hventasanticipos = new hVentaAnticipos();
        // vendedores = husuarios.consultaUsuarios("puesto", "=", "Ventas");
        vendedores = husuarios.consultaUsuarios("", "*", "");
        
        df = new DecimalFormat("0.00");
        df2 = new DecimalFormat("0.000");
        
        vectorEncabezado = new Vector();
        vector = new Vector();
        
        vectorEncabezado.add("Vendedor");
        vectorEncabezado.add("C. Ventas");
        vectorEncabezado.add("Imp. Ventas");
        vectorEncabezado.add("C. V.Reservaciones");
        vectorEncabezado.add("Imp. V.Reservaciones");
        vectorEncabezado.add("C. Ant. Nuevos");
        vectorEncabezado.add("Imp. Ant. Nuevos");
        vectorEncabezado.add("C. Ant. Usados");
        vectorEncabezado.add("Imp. Ant. Usados");
        vectorEncabezado.add("Total Ventas");
        vectorEncabezado.add("T.Importe");
        vectorEncabezado.add("T.Importe S/Iva");
        vectorEncabezado.add("Comisión");
        vectorEncabezado.add("C. Devoluciones");
        vectorEncabezado.add("Imp. Devoluciones");
        vectorEncabezado.add("Imp. Devoluciones S/Iva");
        vectorEncabezado.add("Comisión Devoluciones");
        vectorEncabezado.add("Total Neto");

        
        dtm = new DefaultTableModel(vector, vectorEncabezado) {

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              };
        jTable1.setModel(dtm);  
        
        
        jTable1.getColumn("Vendedor").setPreferredWidth(150);
        jTable1.getColumn("C. Ventas").setPreferredWidth(30);
        jTable1.getColumn("Imp. Ventas").setPreferredWidth(70);
        jTable1.getColumn("C. V.Reservaciones").setPreferredWidth(30);
        jTable1.getColumn("Imp. V.Reservaciones").setPreferredWidth(70);
        jTable1.getColumn("C. Ant. Nuevos").setPreferredWidth(30);
        jTable1.getColumn("Imp. Ant. Nuevos").setPreferredWidth(70);
        jTable1.getColumn("C. Ant. Usados").setPreferredWidth(30);
        jTable1.getColumn("Imp. Ant. Usados").setPreferredWidth(70);
        jTable1.getColumn("C. Devoluciones").setPreferredWidth(30);
        jTable1.getColumn("Imp. Devoluciones").setPreferredWidth(70);
    //   jTable1.getColumn("Cantidad").setPreferredWidth(100);
    //    jTable1.getColumn("Cantidad").setPreferredWidth(20);
        listaComisiones = new ArrayList<ReporteComisiones>();
        
    }
    
}
