/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paedeias.vistas;

import com.paedeias.controladores.CConfiguracion;
import com.paedeias.controladores.CGlobalConfig;
import com.paedeias.controladores.CPrincipal;
import com.paedeias.controladores.impresiones.ImpresionCancelacionCompras;
import com.paedeias.controladores.impresiones.ImpresionVenta;
import com.paedeias.controladores.impresiones.PageableText;
import com.paedeias.helpers.*;
import com.paedeias.identidades.*;
import java.awt.Color;
import java.awt.Window;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALL
 */
public class VDevolver_Pedidos extends javax.swing.JPanel {

    /**
     * Creates new form VAltaCompras
     */
    public VDevolver_Pedidos(ComprasMayoreo compras) {
        initComponents();
        inicializar(compras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Artículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Proveedor");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Referencia");

        jTextField12.setEditable(false);
        jTextField12.setText("0");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Escala");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Factura");

        jTextField18.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de los Artículos Registrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Cantidad a Devolver:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Motivo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Referencia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Partidas");

        jLabel16.setText("0000");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Subtotal");

        jLabel18.setText("0000.00");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("IVA");

        jLabel24.setText("0000");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Total");

        jLabel26.setText("0000.00");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Cantidad");

        jLabel33.setText("0000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Observaciones");

        jTextField16.setEditable(false);

        jButton1.setBackground(new java.awt.Color(11, 70, 119));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Devolver Parcial");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(11, 70, 119));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Devolver Completa");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(11, 70, 119));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reimprimir");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
        
        ConexionWeb conexionweb = new ConexionWeb();
        String transaccion="";
        
        try{
        boolean bankar=true;
        
        hKardex hkar = new hKardex();
        hAlmacendevoluciones halmacendevoluciones = new hAlmacendevoluciones();
        for(int i=0; i<respaldopr.size(); i++)
        {
        if(respaldopr.get(i).getDevuelta() > 0)
        {
            
        Kardex parkar = hkar.consultaUltimoRenglon("articulo", "=", respaldopr.get(i).getArticulo());
        
        if(parkar == null)
        {
            JOptionPane.showMessageDialog(null, "Este artículo no se encuentra registrado en Kardex");
            bankar = false;
        }
        
        if(Integer.compare(parkar.getExistencias(),respaldopr.get(i).getDevuelta()) < 0)
        {
            JOptionPane.showMessageDialog(null, "La existencia en el artículo "+respaldopr.get(i).getArticulo() + "es mayor que la disponible en Kardex, consulte a un Administrador para modificar existencia");
            bankar = false;
        }
        
        listaArticulos = articulos.consultaArticulos("codigo", "=", respaldopr.get(i).getArticulo()); // se valida que haya existencia suficiente en almacen general para hacer la dev.
        if(!listaArticulos.isEmpty())
        {
          int validaArt = (int)listaArticulos.get(0).getExistencia() - respaldopr.get(i).getDevuelta();  
          if(validaArt < 0)
          {
            List<Almacendevoluciones> validadev = halmacendevoluciones.consultaPartidasAlmacen("codigoArticulo", "=", listaArticulos.get(0).getCodigo());
            if(!validadev.isEmpty())
            {   
                bankar = false;
                for(int idev=0; idev<validadev.size(); idev++)
                    {
                        if(validadev.get(idev).getCantidad() >= respaldopr.get(i).getDevuelta())
                        {
                            bankar = true;
                        }
                    }
          if(bankar == false)
                {
          JOptionPane.showMessageDialog(null, "No existe existencia suficiente en ningún catálogo para hacer esta devolución");             
                }
            }
         else
        {
         JOptionPane.showMessageDialog(null, "No existe existencia suficiente en el catálogo de artículos para hacer esta devolución");   
         return;
        }
          }
        }else
        {
         JOptionPane.showMessageDialog(null, "No existe el código que desea devolver en el catálogo de artículos");   
         return;
        }
        
        }
        
        }
        if(bankar==false)
            return;
         
        int eleccion=JOptionPane.showConfirmDialog(null, "¿Está seguro de querer devolver esta compra?");
        
        if(eleccion == JOptionPane.YES_OPTION)
        {      
        
         VConfirmaAlmacenista2 confirmaalmacenista = new VConfirmaAlmacenista2((JFrame)Window.getWindows()[0],true);
                confirmaalmacenista.setLocationRelativeTo(null);
                confirmaalmacenista.setVisible(true);
                if(confirmaalmacenista.isExito())
                {
        
        int it0 = 0;
        boolean bandera = true;
        while(it0 < respaldopr.size())
        {
        if(respaldopr.get(it0).getDevuelta() != 0)
        bandera = false;    
        it0++;
        }
        if(bandera)
        {
        JOptionPane.showMessageDialog(null,"No se ha seleccionado ninguna partida por devolver");    
        return;
        }
        
        if(!CPrincipal.getConexion().crearTransaccion())
        return;
        
        if(CGlobalConfig.isWeb())
        transaccion = conexionweb.iniciarTransaccion() + " ";
        
        hCuentasPorPagar fecha = new hCuentasPorPagar();  
        List<Partidas> partidasd = new ArrayList<Partidas>();
        
        int it1 = 0;
        while(it1 < respaldopr.size())
        {
            if(respaldopr.get(it1).getDevuelta() > 0)
            {
             int devolver = respaldopr.get(it1).getCantidad() - respaldopr.get(it1).getDevuelta();
             int respaldoDev = respaldopr.get(it1).getDevuelta();
             int agregarDev = respaldopr.get(it1).getDevuelta() + listapr.get(it1).getDevuelta();
             respaldopr.get(it1).setCantidad(devolver);
             respaldopr.get(it1).setDevuelta(agregarDev);
             
             
             respaldopr.get(it1).setSubtotal(respaldopr.get(it1).getCostoDesc() * devolver);
             
             //se hace la devolución en las partidas de compras
             
             
             listaArticulos = articulos.consultaArticulos("codigo", "=", respaldopr.get(it1).getArticulo());
             
             if(!listaArticulos.isEmpty())
             {
             respaldopr.get(it1).setTotal(respaldopr.get(it1).getSubtotal() + (respaldopr.get(it1).getSubtotal() * (double)listaArticulos.get(0).getIva()/100));    
             }
             
             if(!CGlobalConfig.isWeb())
             hpartidascompras.actualizarPCompras(respaldopr.get(it1), "id", "=", String.valueOf(respaldopr.get(it1).getId()));
             else
             transaccion = transaccion + hpartidascompras.crearQueryActualizarPCompras(respaldopr.get(it1), "id", "=", String.valueOf(respaldopr.get(it1).getId())) + " ";
             
             respaldopr.get(it1).setDevuelta(respaldoDev);
             
             //se hace la devolución en el kardex
              Kardex renglon = new Kardex();
              kardex = hkardex.consultaUltimoRenglon("articulo", "=", respaldopr.get(it1).getArticulo());
           
           if(kardex == null)
           {
                                 //Se registra la pieza en Kardex
                    kardex = new Kardex();
                    kardex.setAlmacenista("");
                    kardex.setAnticipos(listaArticulos.get(0).getAnticipos());
                    kardex.setArticulo(listaArticulos.get(0).getCodigo());
                    kardex.setEntrada(0);
                    kardex.setExistencias((int)listaArticulos.get(0).getExistencia());
                    kardex.setIdArticulo(listaArticulos.get(0).getId());
                    kardex.setModificacion("Registro");
                    kardex.setMovimiento("Registro de Artículo");
                    kardex.setNoMov("1");
                    kardex.setPrecioVenta(listaArticulos.get(0).getPrecioVenta());
                    kardex.setRefFerrari("Registro");
                    kardex.setReservados((int)listaArticulos.get(0).getReservado());
                    kardex.setResponsable("1");
                    kardex.setResponsable2("Registro Automático");
                    kardex.setSalida(0);
                    kardex.setUltimoCosto(listaArticulos.get(0).getUltimoCosto());
                    kardex.setVendidoEn(0.0);
                    
                if(!CGlobalConfig.isWeb())
                hkardex.guardarEnKardex(kardex); 
                else
                transaccion = transaccion + hkardex.crearQueryGuardarEnKardexCompleto(kardex) + " ";  
           }
                               
                    renglon.setAlmacenista("");
                    renglon.setAnticipos(kardex.getAnticipos());
                    renglon.setArticulo(kardex.getArticulo());
                    renglon.setEntrada(0);
                    renglon.setExistencias(kardex.getExistencias() - respaldopr.get(it1).getDevuelta());
                    renglon.setIdArticulo(kardex.getIdArticulo());
                    renglon.setModificacion(respaldopr.get(it1).getReferencia()+" "+respaldopr.get(it1).getMotivoDevolucion());
                    renglon.setMovimiento("Devolución Compra "+ compras.getId());
                    renglon.setNoMov(String.valueOf(Integer.valueOf(kardex.getNoMov())+1));
                    renglon.setPrecioVenta(respaldopr.get(it1).getPrecioVenta());
                    renglon.setRefFerrari("Devolución Ref. "+jTextField18.getText());
                    renglon.setReservados(kardex.getReservados());
                    renglon.setResponsable(String.valueOf(confirmaalmacenista.getIdalmacenista()));
                    renglon.setResponsable2(confirmaalmacenista.getNombreAdministrador());
                    renglon.setSalida(respaldopr.get(it1).getDevuelta());
                    renglon.setUltimoCosto(respaldopr.get(it1).getCostoDesc());
                    renglon.setVendidoEn(0.0);
                    
                    if(!CGlobalConfig.isWeb())
                    hkardex.guardarEnKardex(renglon); 
                    else
                    transaccion = transaccion + hkardex.crearQueryGuardarEnKardexCompleto(renglon) + " ";
                    
                    // se hace la devolución en el catálogo de artículos             
                    
                    int devolverArt = (int)listaArticulos.get(0).getExistencia() - respaldopr.get(it1).getDevuelta();
                    
                    if(devolverArt < 0)
                    {
                    
                    List<Almacendevoluciones> almacendev = halmacendevoluciones.consultaPartidasAlmacen("codigoArticulo", "=", listaArticulos.get(0).getCodigo());
                    if(!almacendev.isEmpty())
                    {
                    for(int i=0; i<almacendev.size(); i++)
                    {
                        if(almacendev.get(i).getCantidad() >= respaldopr.get(it1).getDevuelta())
                        {
                            devolverArt = almacendev.get(i).getCantidad() - respaldopr.get(it1).getDevuelta();
                            
                            if(!CGlobalConfig.isWeb())
                            halmacendevoluciones.actualizarExistencias(almacendev.get(i).getId(),devolverArt);
                            else
                            transaccion = transaccion + halmacendevoluciones.crearQueryActualizarExistencias(almacendev.get(i).getId(),devolverArt) + " ";    
                            
                            int devAlm = listaArticulos.get(0).getAlmacenDevoluciones() - respaldopr.get(it1).getDevuelta();
                            
                            if(!CGlobalConfig.isWeb())
                            articulos.actualizarExistenciasDev(listaArticulos.get(0).getCodigo(),devAlm);
                            else
                            transaccion = transaccion + articulos.crearQueryActualizarExistenciasDev(listaArticulos.get(0).getCodigo(),devAlm) + " ";    
                            
                            i = almacendev.size();
                        }
                    }
                    
                    
                    }
                    
                    }else
                    {
                    listaArticulos.get(0).setExistencia(devolverArt);
                    
                    if(!CGlobalConfig.isWeb())
                    articulos.actualizarArticulos(listaArticulos.get(0), "codigo", "=", listaArticulos.get(0).getCodigo());
                    else
                    transaccion = transaccion + articulos.crearQueryActualizarArticulos(listaArticulos.get(0), "codigo", "=", listaArticulos.get(0).getCodigo()) + " ";    
                    
                    }
                    
                    Partidas partidad = new Partidas();
                    partidad.setDescripcionArticulo(respaldopr.get(it1).getDescripcion());
                    partidad.setCantidad(respaldopr.get(it1).getDevuelta());
                    partidad.setConBeneficio(respaldopr.get(it1).getCostoDesc());
                    partidad.setCodigoArticulo(respaldopr.get(it1).getArticulo());
                    partidasd.add(partidad);
            }   
            it1++;
        }
        
        //se cambian los subtotales de la compra
        compras.setDevolucion(1);
        compras.setImporte(compras.getImporte()-Double.valueOf(jLabel26.getText()));
        
        if(!CGlobalConfig.isWeb())
        hcompras.actualizarComprasLast(compras, "id", "=", String.valueOf(compras.getId()));
        else
        transaccion = transaccion + hcompras.crearQueryActualizarComprasLast(compras, "id", "=", String.valueOf(compras.getId())) + " ";
        
       List<Cuentasporpagar> cpp = fecha.consultaCuentasPorPagar("compra", "=", String.valueOf(compras.getId()));
       if(!cpp.isEmpty())
       {
       cpp.get(0).setSaldo(compras.getImporte());    
       
       if(!CGlobalConfig.isWeb())
       fecha.actualizarCuentasPorPagar(cpp.get(0), "id", "=", String.valueOf(cpp.get(0).getId()));
       else
       transaccion = transaccion + fecha.crearQueryActualizarCuentasPorPagar(cpp.get(0), "id", "=", String.valueOf(cpp.get(0).getId())) + " ";    
       
       }
        CPrincipal.getConexion().finalizarTransaccion();
        
        if(CGlobalConfig.isWeb())
               {
               transaccion = transaccion + conexionweb.finalizarTransaccion();    
               conexionweb.escribirEnWeb(transaccion);
               }
        
        //se imprime
         try
        {       
  
        ImpresionCancelacionCompras icc = new ImpresionCancelacionCompras();
        icc.inicializar("",jTextField16.getText(),CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  compras.getFechaCompra(),partidasd,jComboBox3.getSelectedItem().toString(),jTextField12.getText(),
                                                  jTextField18.getText(),jLabel18.getText(),jLabel24.getText(),jLabel26.getText(),
                                                  CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  jTextField16.getText(),fecha.generarFecha()
                );
        PrinterJob job = PrinterJob.getPrinterJob();
        // job.setPrintable(icc);
        // PageFormat format = job.pageDialog(job.defaultPage());
        
        PageFormat format = new PageFormat();
        
        
        Paper p = new Paper();
        
        p.setSize(CGlobalConfig.getAnchoImp(),CGlobalConfig.getAltoImp());
        p.setImageableArea(CGlobalConfig.getxImp(),CGlobalConfig.getyImp(),CGlobalConfig.getAnchoImp(),CGlobalConfig.getAltoImp());
        format.setPaper(p);
        
        job.setPageable(new PageableText(icc.generarCadenaImpresion(), format));
        if (job.printDialog())
            job.print();
        }       catch (IOException ex) {
                    Logger.getLogger(VDevolver_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
                }catch (PrinterException ex) {
            Logger.getLogger(ImpresionVenta.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        JOptionPane.showMessageDialog(null, "Devolución Exitosa!");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }
        }
        
        }catch(Exception e)
        {
            CPrincipal.getConexion().cancelarTransaccion();
            e.printStackTrace();            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String motivo = JOptionPane.showInputDialog("¿Por qué deseas devolver esta compra?");
        
        int it1=0;
        while(it1<respaldopr.size())
        {
            respaldopr.get(it1).setDevuelta(respaldopr.get(it1).getCantidad());
            respaldopr.get(it1).setReferencia(jTextField4.getText());
            respaldopr.get(it1).setMotivoDevolucion(motivo);
            it1++;
        }
        jButton1.doClick();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        
              if(evt.getClickCount() == 2)
            {   
                
            if(jTable2.getSelectedRow() == -1)    
                return;
                
                
            if(Boolean.valueOf(dtmPartidas.getValueAt(jTable2.getSelectedRow(), 8).toString()))
            {
            dtmPartidas.setValueAt(false, jTable2.getSelectedRow(), 8);
            dtmPartidas.setValueAt("0", jTable2.getSelectedRow(), 7);
            dtmPartidas.setValueAt(String.valueOf(respaldopr.get(jTable2.getSelectedRow()).getCantidad()) , jTable2.getSelectedRow(), 6);
            
            double tempsub = Double.valueOf(jLabel18.getText()) - (respaldopr.get(jTable2.getSelectedRow()).getCostoDesc() * respaldopr.get(jTable2.getSelectedRow()).getDevuelta());
            hArticulos harticulos = new hArticulos();
            List<Articulos> articulo = harticulos.consultaArticulos("codigo", "=", respaldopr.get(jTable2.getSelectedRow()).getArticulo());
            int ariva = 0;
            if(!articulo.isEmpty())
            {
                ariva = articulo.get(0).getIva();
            }
            
            double tempiva = tempsub * ((double)ariva/100);
            double temptotal = tempsub + tempiva;
            int tempcantidad = Integer.valueOf(jLabel33.getText()) -  respaldopr.get(jTable2.getSelectedRow()).getDevuelta();
            
            jLabel18.setText(df.format(tempsub));
            jLabel24.setText(df.format(tempiva));
            jLabel26.setText(df.format(temptotal));
            jLabel33.setText(String.valueOf(tempcantidad));
            
            respaldopr.get(jTable2.getSelectedRow()).setDevuelta(0);
            respaldopr.get(jTable2.getSelectedRow()).setReferencia("00000");
            respaldopr.get(jTable2.getSelectedRow()).setMotivoDevolucion("Sin Motivo");
            
            }
            else
            {
                
            if(jTextField2.getText().isEmpty())    
            {
              JOptionPane.showMessageDialog(null, "Por favor indique la cantidad a devolver en esta partida");  
              return;  
            }    
                
            if(Integer.valueOf(jTextField2.getText()) > respaldopr.get(jTable2.getSelectedRow()).getCantidad())    
            {
              JOptionPane.showMessageDialog(null, "No se puede devolver una cantidad mayor a la cantidad comprada");  
              return;  
            }
            
                
            dtmPartidas.setValueAt(true, jTable2.getSelectedRow(), 8);          
            dtmPartidas.setValueAt(jTextField2.getText(), jTable2.getSelectedRow(), 7);
            dtmPartidas.setValueAt(String.valueOf(respaldopr.get(jTable2.getSelectedRow()).getCantidad() - Integer.valueOf(jTextField2.getText()) ) , jTable2.getSelectedRow(), 6);
            
            respaldopr.get(jTable2.getSelectedRow()).setDevuelta(Integer.valueOf(jTextField2.getText()));
            respaldopr.get(jTable2.getSelectedRow()).setReferencia(jTextField4.getText());
            respaldopr.get(jTable2.getSelectedRow()).setMotivoDevolucion(jTextField3.getText());
            
            double tempsub = Double.valueOf(jLabel18.getText()) + (respaldopr.get(jTable2.getSelectedRow()).getCostoDesc() * Integer.valueOf(jTextField2.getText()));
            hArticulos harticulos = new hArticulos();
            List<Articulos> articulo = harticulos.consultaArticulos("codigo", "=", respaldopr.get(jTable2.getSelectedRow()).getArticulo());
            int ariva = 0;
            if(!articulo.isEmpty())
            {
                ariva = articulo.get(0).getIva();
            }
            
            
            double tempiva = tempsub * ((double)ariva/100);
            double temptotal = tempsub + tempiva;
            int tempcantidad = Integer.valueOf(jLabel33.getText()) +  Integer.valueOf(jTextField2.getText());
            
            jLabel18.setText(df.format(tempsub));
            jLabel24.setText(df.format(tempiva));
            jLabel26.setText(df.format(temptotal));
            jLabel33.setText(String.valueOf(tempcantidad));
            
            }  
            }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        List<Partidas> partidasd= new ArrayList<Partidas>();
        hArticulos harticulos = new hArticulos();
        double tempsub = 0;
        double tempiva = 0;
        double temptot = 0;
        
        int it1=0;
        while(it1<listapr.size())
        {
            
            if(listapr.get(it1).getDevuelta() != 0)
            {
            Partidas par = new Partidas();
            par.setDescripcionArticulo(listapr.get(it1).getDescripcion());
            par.setCantidad(listapr.get(it1).getDevuelta());
            par.setConBeneficio(listapr.get(it1).getCostoDesc());
            par.setCodigoArticulo(listapr.get(it1).getArticulo());
            partidasd.add(par);
            
            double arsub = listapr.get(it1).getCostoDesc() * listapr.get(it1).getDevuelta();
            double ariva = 0.0;
            List<Articulos> articulo = harticulos.consultaArticulos("codigo", "=", listapr.get(it1).getArticulo());
            int iva = 0;
            if(!articulo.isEmpty())
            {
                iva = articulo.get(0).getIva();
            }
            ariva = arsub * ((double)iva/100);
            
            tempiva = tempiva + ariva;
            tempsub = tempsub + arsub;
            
            }    
            it1++;
        }
        
        temptot = tempsub + tempiva;
        
         //se imprime
         try
        {       
        hCuentasPorPagar fecha = new hCuentasPorPagar();    
        ImpresionCancelacionCompras icc = new ImpresionCancelacionCompras();
        icc.inicializar("",jTextField16.getText(),CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  compras.getFechaCompra(),partidasd,jComboBox3.getSelectedItem().toString(),jTextField12.getText(),
                                                  jTextField18.getText(),df.format(tempsub),df.format(tempiva),df.format(temptot),
                                                  CConfiguracion.getNombres() + " "+ CConfiguracion.getApellidoP() + " "+ CConfiguracion.getApellidoM(),
                                                  jTextField16.getText(),fecha.generarFecha()
                );
        PrinterJob job = PrinterJob.getPrinterJob();
        // job.setPrintable(icc);
        // PageFormat format = job.pageDialog(job.defaultPage());
        
        PageFormat format = new PageFormat();
        
        
        Paper p = new Paper();
        
        p.setSize(CGlobalConfig.getAnchoImp(),CGlobalConfig.getAltoImp());
        p.setImageableArea(CGlobalConfig.getxImp(),CGlobalConfig.getyImp(),CGlobalConfig.getAnchoImp(),CGlobalConfig.getAltoImp());
        format.setPaper(p);
        
        job.setPageable(new PageableText(icc.generarCadenaImpresion(), format));
        if (job.printDialog())
            job.print();
        } catch (IOException ex) {
            Logger.getLogger(VDevolver_Pedidos.class.getName()).log(Level.SEVERE, null, ex);
        }catch (PrinterException ex) {
            Logger.getLogger(ImpresionVenta.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void limpiar()
    {
        
        listapr.clear();
        listaArticulos.clear();
        jComboBox3.setSelectedIndex(0);
        jTextField12.setText("0");
        vector.removeAllElements();
        dtm.fireTableDataChanged();
        vectorPartidas.removeAllElements();
        dtmPartidas.fireTableDataChanged();
        jLabel16.setText("0000");
        jLabel18.setText("0000.00");
        jLabel24.setText("0000");
        jLabel26.setText("0000.00");
        jLabel33.setText("0000");
        jTextField16.setText("");
        jTextField18.setText("");
        
        subtotal=0.00;
        iva=0.0;
        total = 0.0;
        desadi = 0.0;

    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    hArticulos articulos;
    hComprasMayoreo hcompras;
    hPartidasComprasMayoreo hpartidascompras;
    List<Articulos> listaArticulos;
    List<Articulos> actualizarArticulos;
    List<Partidascomprasmayoreo> listapr,respaldopr;
    Vector vector,vectorPartidas;
    hAlmacendevoluciones halmacendevoluciones;
    DefaultTableModel dtm,dtmPartidas;
    Vector<String> encabezadoArticulos,encabezadoPartidas;
    List <Proveedores> proveedor;
    hProveedores hproveedor;
    ComprasMayoreo compras;
    Double subtotal=0.00;
    Double iva=0.0;
    Double total = 0.0;
    Double desadi = 0.0;
    Integer cantidadAr=0;
    DecimalFormat df;
    Kardex kardex;
    hKardex hkardex;
    boolean click=false; 
    hArticuloProveedor harticuloproveedor;
    boolean bandera=false;
    Double importeConIva = 0.0;
    Double cargos = 0.0;
    Double descuento = 0.0;
    Double porcostodesc = 0.0;
    Double importeCompra = 0.0;
    Integer porcentajeDesc = 0;
    Integer porcentajeCosto = 0;
    Integer cascada = 0;
    Integer ivaArticulo=0;
    
    
    private void inicializar(ComprasMayoreo compra) {
        
    kardex = new Kardex();
    hkardex = new hKardex();
    harticuloproveedor = new hArticuloProveedor();
    df = new DecimalFormat("0.00");
    articulos = new hArticulos();
    listaArticulos = new ArrayList<Articulos>();
    actualizarArticulos = new ArrayList<Articulos>();
    halmacendevoluciones = new hAlmacendevoluciones();
    
        encabezadoArticulos = new Vector<String>();
        encabezadoArticulos.add("Código");
        encabezadoArticulos.add("Descripción");
        encabezadoArticulos.add("Compra");
        encabezadoArticulos.add("Ultimo Costo");
        encabezadoArticulos.add("Precio Venta");
        encabezadoArticulos.add("Existencia");
        encabezadoArticulos.add("En A. Devoluciones");
        encabezadoArticulos.add("Reservados");
        
        
        vector = new Vector();
    dtm = new DefaultTableModel(vector,encabezadoArticulos) {

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              };

           
           proveedor = new ArrayList<Proveedores>();
           hproveedor = new hProveedores();
           proveedor = hproveedor.consultaProveedores("id","=",String.valueOf(compra.getCodigoProveedor()));
           
           int indprov = 0;
           while(indprov < proveedor.size()) 
           {
               jComboBox3.addItem(proveedor.get(indprov).getNombre());
               jComboBox4.addItem(proveedor.get(indprov).getDesc1());
               jComboBox4.addItem(proveedor.get(indprov).getDesc2());
               jComboBox4.addItem(proveedor.get(indprov).getDesc3());
               jComboBox4.addItem(proveedor.get(indprov).getDesc4());
               jComboBox4.addItem(proveedor.get(indprov).getDesc5());
               jComboBox4.addItem(proveedor.get(indprov).getDesc6());

               indprov++;
           }
           
           compras = new ComprasMayoreo();
           compras.setBanco(compra.getBanco());
           compras.setCargos(compra.getCargos());
           compras.setCheque(compra.getCheque());
           compras.setCodigoPedido(compra.getCodigoPedido());
           compras.setCodigoProveedor(compra.getCodigoProveedor());
           compras.setCompra(compra.getCompra());
           compras.setDescAdic(compra.getDescAdic());
           compras.setDevolucion(compra.getDevolucion());
           compras.setDiasCred(compra.getDiasCred());
           compras.setFechaCompra(compra.getFechaCompra());
           compras.setImporte(compra.getImporte());
           compras.setNumRefComp(compra.getNumRefComp());
           compras.setObservacion(compra.getObservacion());
           compras.setPedido(compra.getPedido());
           compras.setTipoPago(compra.getTipoPago());
           compras.setId(compra.getId());
           compras.setFactura(compra.getFactura());
           compras.setIdUsuario(compra.getIdUsuario());
           compras.setCantidadArticulos(compra.getCantidadArticulos());
           compras.setTn(compra.getTn());
           
           hcompras = new hComprasMayoreo();
           
        jTextField18.setText(compras.getFactura());
        jTextField12.setText(compras.getNumRefComp());
        
        
        jTextField16.setText(compras.getObservacion());
        
        
           
           
        hpartidascompras = new hPartidasComprasMayoreo();   
        listapr = new ArrayList<Partidascomprasmayoreo>();
        respaldopr = new ArrayList<Partidascomprasmayoreo>();
        listapr = hpartidascompras.consultaPComprasNoDevueltas("compra", "=", String.valueOf(compras.getId()));
        encabezadoPartidas = new Vector<String>();
        encabezadoPartidas.add("Código");
        encabezadoPartidas.add("Descripción");
        encabezadoPartidas.add("Costo con Descuento");
        encabezadoPartidas.add("Subtotal");
        encabezadoPartidas.add("Total");
        encabezadoPartidas.add("Cantidad");
        encabezadoPartidas.add("Cantidad no Devuelta");
        encabezadoPartidas.add("Cantidad a Devolver");
        encabezadoPartidas.add("Devolver");
        vectorPartidas = new Vector();
        
        double subT=0;
        double tot=0;
        double iva=0;
        int canti=0;
 
           
           for(Object o : listapr)
           {
           Partidascomprasmayoreo pc =  (Partidascomprasmayoreo)o;       
               
           Partidascomprasmayoreo partidarespaldo = new Partidascomprasmayoreo();
           partidarespaldo.setArticulo(pc.getArticulo());
           partidarespaldo.setCantidad(pc.getCantidad());    
           partidarespaldo.setCargoArticulo(pc.getCargoArticulo());
           partidarespaldo.setCompra(pc.getCompra());
           partidarespaldo.setCostoDesc(pc.getCostoDesc());
           partidarespaldo.setDescripcion(pc.getDescripcion());
           partidarespaldo.setDescuento(pc.getDescuento());
           partidarespaldo.setDescuentoArti(pc.getDescuentoArti());
           partidarespaldo.setDevuelta(0);
           partidarespaldo.setIva(pc.getIva());
           partidarespaldo.setMontoIva(pc.getMontoIva());
           partidarespaldo.setPorcCargo(pc.getPorcCargo());
           partidarespaldo.setPrecioUni(pc.getPrecioUni());
           partidarespaldo.setPrecioVenta(pc.getPrecioVenta());
           partidarespaldo.setSubtotal(pc.getSubtotal());
           partidarespaldo.setTotal(pc.getTotal());
           partidarespaldo.setPrecioCompra(pc.getPrecioCompra());
           partidarespaldo.setStockMin(pc.getStockMin());
           partidarespaldo.setStockMax(pc.getStockMax());
           partidarespaldo.setUtilidad(pc.getUtilidad());
           partidarespaldo.setCascada(pc.getCascada());
           partidarespaldo.setId(pc.getId());
           partidarespaldo.setMotivoDevolucion(pc.getMotivoDevolucion());
           partidarespaldo.setReferencia(pc.getReferencia());
           partidarespaldo.setCadenaCascada(pc.getCadenaCascada());
           respaldopr.add(partidarespaldo);    
           
           Vector<Object> unaFila = new Vector<Object>();
           unaFila.add(pc.getArticulo());
           unaFila.add(pc.getDescripcion());
           unaFila.add(df.format(pc.getCostoDesc()));
           unaFila.add(df.format(pc.getSubtotal()));
           unaFila.add(df.format(pc.getTotal()));
           unaFila.add(pc.getCantidad());
           unaFila.add(pc.getCantidad());
        //   unaFila.add(pc.getCantidad() - pc.getDevuelta());
        //   if(pc.getDevuelta() == 0)
        //   {
               unaFila.add(0);
        /*   if(pc.getCantidad() - pc.getDevuelta() < 0)    
           {
               unaFila.add(true);
               System.out.println("Hay una pieza que no se puede devolver");
           }
           * else */
               unaFila.add(false);
        //   }
        /*   else
           {
               subT = subT + (pc.getDevuelta() * pc.getCostoDesc());
               iva = iva + (pc.getDevuelta() * pc.getCostoDesc() * (double)pc.getIva()/100);
               tot = subT + iva;
               canti = canti + pc.getDevuelta();
             unaFila.add(pc.getDevuelta());
               unaFila.add(true);
           } */
           
           vectorPartidas.add(unaFila);
           }
           
           dtmPartidas = new DefaultTableModel(vectorPartidas,encabezadoPartidas) {

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              
              @Override
              public Class<?> getColumnClass(int columnIndex) {
              if (columnIndex == 8) {
              return Boolean.class;
               }
               return super.getColumnClass(columnIndex);
                }
              };
           
           

           jTable2.setModel(dtmPartidas);   
           jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
           jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
        if(jTable2.getRowCount()>0||jTable2.getRowCount()<listapr.size())
        {  
            try{
                if(jTable2.getSelectedRow() > -1)
                {
                
                
                if(Boolean.valueOf(dtmPartidas.getValueAt(jTable2.getSelectedRow(), 7).toString()))
                {
                jTextField2.setText(String.valueOf(respaldopr.get(jTable2.getSelectedRow()).getDevuelta()));
                }else
                jTextField2.setText("");
                jTextField3.setText(String.valueOf(respaldopr.get(jTable2.getSelectedRow()).getMotivoDevolucion()));
                jTextField4.setText(String.valueOf(respaldopr.get(jTable2.getSelectedRow()).getReferencia()));
                
                }
            }catch(java.lang.ArrayIndexOutOfBoundsException exe)
            {
                System.out.println("");
            }
           
        }
            }
        }); 
           
          
     /*     int it1=0;
          while(it1 < listapr.size())
          {
              total = total + listapr.get(it1).getTotal();
              cantidadAr = cantidadAr + listapr.get(it1).getCantidad();
              it1++;
          }
          
          subtotal = total/(1+CGlobalConfig.getIvaVenta());
          
          iva = total - subtotal;
          
          jLabel16.setText(String.valueOf(listapr.size()));
          jLabel18.setText(df.format(subtotal));
          jLabel24.setText(df.format(iva));
          jLabel26.setText(df.format(total));
          jLabel33.setText(String.valueOf(cantidadAr));
          */
        jLabel16.setText(String.valueOf(listapr.size()));   
        if(compras.getCompra() == 1)
        { 
        jTextField16.setEditable(false);  
        jComboBox4.setEnabled(false);
        jTextField16.setText(listapr.get(0).getMotivoDevolucion()+" - "+compras.getObservacion());
        // jButton1.setEnabled(false);    
        // jButton2.setEnabled(false);    
        
        }
        
        if(compras.getDevolucion() == 1)
        {
        setBackground(Color.RED);    
        }
        
    /*    if(compras.getDevolucion() == 1)
        {
         jButton1.setEnabled(false);   
         jButton2.setEnabled(false);   
         jButton3.setEnabled(true);   
         
         jLabel16.setText(String.valueOf(listapr.size()));
         jLabel33.setText(String.valueOf(canti));         
         jLabel18.setText(df.format(subT));
         jLabel24.setText(df.format(iva));
         jLabel26.setText(df.format(tot));
         
         vectorPartidas.clear();
         for(Object o : listapr)
         {
         Partidascomprasmayoreo pc =  (Partidascomprasmayoreo)o;
         Vector<Object> unaFila = new Vector<Object>();
         if(pc.getDevuelta() != 0)
            {
         unaFila.add(pc.getArticulo());
         unaFila.add(pc.getDescripcion());
         unaFila.add(df.format(pc.getCostoDesc()));
         unaFila.add(df.format(pc.getSubtotal()));
         unaFila.add(df.format(pc.getTotal()));
         unaFila.add(pc.getCantidad());
         unaFila.add(pc.getCantidad() - pc.getDevuelta());
         unaFila.add(pc.getDevuelta());
         unaFila.add(true);
         vectorPartidas.add(unaFila);
            }
         }
         dtmPartidas.fireTableDataChanged();
         
         setBackground(Color.RED);
         
        } */
        
        
    }
}
