/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paedeias.vistas;

import com.paedeias.controladores.CGlobalConfig;
import com.paedeias.controladores.CPrincipal;
import com.paedeias.controladores.Validadores;
import com.paedeias.helpers.hArticulos;
import com.paedeias.identidades.Articulos;
import java.awt.Window;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALL
 */
public class VRealizarOferta extends javax.swing.JPanel {

    /**
     * Creates new form VRealizarOferta
     */
    public VRealizarOferta() {
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Buscar Artículos");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Id", "Descripción", "Venta", "Compra", "Existencia", "Reservado", "Linea Principal", "Sinónimo Principal", "Código Alterno", "Proveedor Principal", "Clasificación Paretto", "Sin Paretto", "Con Paretto" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("sea");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Limite");

        jTextField2.setText("100");

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox1.setText("Filtro");

        jTextField3.setText("%");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainicons/btn_buscar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Como", "Igual a", "Todos" }));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Agregar con Descuento");

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 102, 102));
        jCheckBox3.setText("Agregar con Utilidad");

        jTextField4.setText("0");

        jButton1.setBackground(new java.awt.Color(11, 70, 119));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(11, 70, 119));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Agregar todos");
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox1)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(11, 70, 119));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Eliminar");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton4.setBackground(new java.awt.Color(11, 70, 119));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Aplicar descuentos");
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(11, 70, 119));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Eliminar todos");
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Precio Venta:");

        jTextField5.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Precio Compra:");

        jTextField6.setEditable(false);

        jButton7.setBackground(new java.awt.Color(11, 70, 119));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Mostrar Artículos en Oferta");
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jLabel4)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                String valores [] = {"codigo","id","descripcion","precioVenta",
        "precioCompra","existencia","reservado","lineaPrincipal","sinonimoPrincipal","codigo2","proveedor","clasificacion","paretto","paretto"};
                String comparadores [] = {"LIKE","=","*"};
                
        String campo = valores[jComboBox1.getSelectedIndex()];
        String compara = comparadores[jComboBox2.getSelectedIndex()];
        String condicion = jTextField1.getText();
        
        if(jComboBox1.getSelectedItem().toString().equals("Sin Paretto"))
           condicion = "1";
        if(jComboBox1.getSelectedItem().toString().equals("Con Paretto"))
           condicion = "0";
        
        
        
         if(jCheckBox1.isSelected())
         listaArticulos = articulos.consultaArticulosFiltro(campo,compara,condicion,jTextField3.getText());
         else
         listaArticulos = articulos.consultaArticulos(campo,compara,condicion);
         vector.clear();

         for(Object o: listaArticulos){
             Articulos iarticulos = (Articulos)o;
             Vector<Object> unaFila = new Vector<Object>();
             unaFila.add(iarticulos.getId());
             unaFila.add(iarticulos.getCodigo());
             unaFila.add(iarticulos.getDescripcion());
             unaFila.add(iarticulos.getLineaPrincipal());
             unaFila.add(df.format(iarticulos.getPrecioVenta()));
             unaFila.add(df.format(iarticulos.getPrecioCompra()));
             unaFila.add(iarticulos.getExistencia());
             
             
     /*        int acumulado = 0;
             List<Almacendevoluciones> listadev = halmacendevoluciones.consultaPartidas("codigoArticulo", "=", iarticulos.getCodigo());
             int suma=0;
             while(suma<listadev.size())
             {
                 acumulado = acumulado + listadev.get(suma).getCantidad();
                 suma++;
             }*/
             unaFila.add(iarticulos.getAlmacenDevoluciones());
             unaFila.add(iarticulos.getReservado()); 
             unaFila.add(iarticulos.getAnticipos());
             vector.add(unaFila); 

         }
       
       dtm.fireTableDataChanged();  
       jTable1.getColumnModel().getColumn(0).setPreferredWidth(50); 
       jTable1.getColumnModel().getColumn(1).setPreferredWidth(150); 
       jTable1.getColumnModel().getColumn(2).setPreferredWidth(600);     
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jButton3.doClick();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            if(jTable1.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Por favor seleccione primero una fila");
            return;
        }
        
        if(listaArticulos.get(jTable1.getSelectedRow()).getOferta()==1)
        {
            JOptionPane.showMessageDialog(null, "Este artículo ya se está vendiendo con un precio especial");
            return;
        }
        
        if(!Validadores.validarEntero("Utilidad/Descuento", jTextField4.getText()))
        {
        return;
        }
        
        if(!listaArticulosP.isEmpty())
        {
        for(int a=0; a<listaArticulosP.size(); a++)
        {
            if(listaArticulosP.get(a).getCodigo().equals(listaArticulos.get(jTable1.getSelectedRow()).getCodigo()))
            {
         JOptionPane.showMessageDialog(null, "Este artículo ya se encuentra en la lista actual");   
         return;                
            }
        }
        }
        
        Articulos articulo = new Articulos();
        articulo.setCodigo(listaArticulos.get(jTable1.getSelectedRow()).getCodigo());
        articulo.setDescripcion(listaArticulos.get(jTable1.getSelectedRow()).getDescripcion());
        articulo.setExistencia(listaArticulos.get(jTable1.getSelectedRow()).getExistencia());
        articulo.setExistenciaAlmacen(listaArticulos.get(jTable1.getSelectedRow()).getExistenciaAlmacen());
        articulo.setPrecioVenta(listaArticulos.get(jTable1.getSelectedRow()).getPrecioVenta());
        articulo.setPrecioCompra(listaArticulos.get(jTable1.getSelectedRow()).getPrecioCompra());
        double precioVenta2 = 0;
        if(jCheckBox2.isSelected())
        precioVenta2 = listaArticulos.get(jTable1.getSelectedRow()).getPrecioVenta() - (listaArticulos.get(jTable1.getSelectedRow()).getPrecioVenta() * (double)(Integer.valueOf(jTextField4.getText()))/100);
        else
        {
        precioVenta2 = listaArticulos.get(jTable1.getSelectedRow()).getPrecioCompra() + (listaArticulos.get(jTable1.getSelectedRow()).getPrecioCompra() * (double)(Integer.valueOf(jTextField4.getText()))/100);
        precioVenta2 = precioVenta2 * (1+CGlobalConfig.getIvaVenta());
        }
        
        
        articulo.setPrecioVenta2(precioVenta2);
        articulo.setOferta(1);
        
        listaArticulosP.add(articulo);
        
             Vector<Object> unaFila = new Vector<Object>();
             unaFila.add(articulo.getCodigo());
             unaFila.add(articulo.getDescripcion());
             unaFila.add(df.format(articulo.getPrecioVenta()));
             unaFila.add(df.format(articulo.getPrecioVenta2()));
             unaFila.add(df.format(articulo.getPrecioCompra()));
             
             double vu = 0;
             vu = articulo.getPrecioCompra() + articulo.getPrecioCompra() * CGlobalConfig.getUtilidad();
             
             if(vu > articulo.getPrecioVenta2())
             unaFila.add("Inválido");    
             else
             unaFila.add("Válido");        
             
             unaFila.add(articulo.getExistencia());
             unaFila.add(articulo.getExistenciaAlmacen());
             vectorPartidas.add(unaFila); 


             
              dtmPartidas.fireTableStructureChanged();

//              jTable2.setModel(dtm2);
              jTable2.getSelectionModel().setSelectionInterval(0, 0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
       if(jTable2.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Por favor seleccione primero una fila");
            return;
        }
        listaArticulosP.remove(jTable2.getSelectedRow());
        
        dtmPartidas.removeRow(jTable2.getSelectedRow());
        dtmPartidas.fireTableStructureChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
                
        if(!Validadores.validarEntero("Utilidad/Descuento", jTextField4.getText()))
        {
        return;
        }
        
        for(int i=0; i<listaArticulos.size(); i++)
        {
          if(listaArticulos.get(i).getOferta()==1)
        {
            JOptionPane.showMessageDialog(null, "Este artículo ya se está vendiendo con un precio especial");
            return;
        }
          
        if(!listaArticulosP.isEmpty())
        {
        for(int a=0; a<listaArticulosP.size(); a++)
        {
            if(listaArticulosP.get(a).getCodigo().equals(listaArticulos.get(i).getCodigo()))
            {
         JOptionPane.showMessageDialog(null, "Este artículo ya se encuentra en la lista actual");   
         return;                
            }
        }
        }
        }
        
        double precioVenta2 = 0;
        double vu = 0;

        for(int i=0; i<listaArticulos.size(); i++)
        {
        Articulos articulo = new Articulos();
        articulo.setCodigo(listaArticulos.get(i).getCodigo());
        articulo.setDescripcion(listaArticulos.get(i).getDescripcion());
        articulo.setExistencia(listaArticulos.get(i).getExistencia());
        articulo.setExistenciaAlmacen(listaArticulos.get(i).getExistenciaAlmacen());
        articulo.setPrecioVenta(listaArticulos.get(i).getPrecioVenta());
        articulo.setPrecioCompra(listaArticulos.get(i).getPrecioCompra());
        if(jCheckBox2.isSelected())
        precioVenta2 = listaArticulos.get(i).getPrecioVenta() - (listaArticulos.get(i).getPrecioVenta() * (double)(Integer.valueOf(jTextField4.getText()))/100);
        else
        {
        precioVenta2 = listaArticulos.get(i).getPrecioCompra() + (listaArticulos.get(i).getPrecioCompra() * (double)(Integer.valueOf(jTextField4.getText()))/100);        
        precioVenta2 = precioVenta2 * (1+CGlobalConfig.getIvaVenta());
        }
        
        articulo.setPrecioVenta2(precioVenta2);
        articulo.setOferta(1);
        
        listaArticulosP.add(articulo);
        
        Vector<Object> unaFila = new Vector<Object>();
             unaFila.add(articulo.getCodigo());
             unaFila.add(articulo.getDescripcion());
             unaFila.add(df.format(articulo.getPrecioVenta()));
             unaFila.add(df.format(articulo.getPrecioVenta2()));
             unaFila.add(df.format(articulo.getPrecioCompra()));
             
             
             vu = articulo.getPrecioCompra() + articulo.getPrecioCompra() * CGlobalConfig.getUtilidad();
             
             if(vu > articulo.getPrecioVenta2())
             unaFila.add("Inválido");    
             else
             unaFila.add("Válido");        
             
             unaFila.add(articulo.getExistencia());
             unaFila.add(articulo.getExistenciaAlmacen());
             vectorPartidas.add(unaFila); 
        }
              dtmPartidas.fireTableStructureChanged();
//              jTable2.setModel(dtm2);
              jTable2.getSelectionModel().setSelectionInterval(0, 0);
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        listaArticulosP.clear();
        vectorPartidas.clear();
        
        dtmPartidas.fireTableStructureChanged();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
         double vu = 0;
         for(int i=0; i<listaArticulosP.size(); i++)
        {
            vu = listaArticulosP.get(i).getPrecioCompra() + (listaArticulosP.get(i).getPrecioCompra() * CGlobalConfig.getUtilidad());
            vu = vu + (vu * CGlobalConfig.getIvaVenta());
            if(vu > listaArticulosP.get(i).getPrecioVenta2()) 
            {
                JOptionPane.showMessageDialog(null, "Existe un artículo con un precio de venta menor al precio de compra en la lista");
                return;
            }
        }
            if(!CPrincipal.getConexion().crearTransaccion())
            return;
        
        for(int i=0; i<listaArticulosP.size(); i++)
        {
            articulos.actualizarOferta(listaArticulosP.get(i).getCodigo(),df.format(listaArticulosP.get(i).getPrecioVenta2()) , listaArticulosP.get(i).getOferta());
        }
        
        jButton4.setEnabled(false);
        JOptionPane.showMessageDialog(null,"Oferta creada");
           CPrincipal.getConexion().finalizarTransaccion();
         
        }catch(Exception e)
        {
            CPrincipal.getConexion().cancelarTransaccion();
            e.printStackTrace();            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        VMostrarArticulosEnOferta seleccionar = new VMostrarArticulosEnOferta((JFrame)Window.getWindows()[0],true);
        seleccionar.setLocationRelativeTo((JFrame)Window.getWindows()[0]);
        seleccionar.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    protected static javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    Vector vector,vectorEncabezado,vectorPartidas,vectorEncabezadoPartidas;
    DecimalFormat df;
    DefaultTableModel dtm;
    DefaultTableModel dtmPartidas;
    List<Articulos> listaArticulos,listaArticulosP;
    ButtonGroup grupo;
    hArticulos articulos;

    private void inicializar() {
        grupo = new ButtonGroup();
        grupo.add(jCheckBox2);
        grupo.add(jCheckBox3);
        
        df = new DecimalFormat("0.00");
        vector = new Vector();
        vectorPartidas = new Vector();
        vectorEncabezado = new Vector<String>();
        vectorEncabezadoPartidas = new Vector<String>();
        listaArticulosP = new ArrayList<Articulos>();
        
        vectorEncabezado.add("Id");
        vectorEncabezado.add("Código");
        vectorEncabezado.add("Descripción");
        vectorEncabezado.add("Línea");
        vectorEncabezado.add("Venta");
        vectorEncabezado.add("Compra");
        vectorEncabezado.add("Existencia");
        vectorEncabezado.add("Almacén Dev.");
        vectorEncabezado.add("Reservaciones");
        vectorEncabezado.add("Anticipos");
        
        vectorEncabezadoPartidas.add("Código");
        vectorEncabezadoPartidas.add("Descripción");
        vectorEncabezadoPartidas.add("Precio Venta");
        vectorEncabezadoPartidas.add("Precio Oferta");
        vectorEncabezadoPartidas.add("Precio Compra");
        vectorEncabezadoPartidas.add("Prec Compra + Util. Min");
        vectorEncabezadoPartidas.add("Existencia");
        vectorEncabezadoPartidas.add("Existencia Almacén Dev.");
        
        dtm = new DefaultTableModel(vector,vectorEncabezado){

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              };
        
        
        
        jTable1.setModel(dtm);
        
        dtmPartidas = new DefaultTableModel(vectorPartidas,vectorEncabezadoPartidas){

              @Override
              public boolean isCellEditable(int row, int column) {
              return false;
                }
              };
        jTable2.setModel(dtmPartidas);
        
        articulos = new hArticulos();
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener(){

            public void valueChanged(ListSelectionEvent e) {
                if(jTable2.getSelectedRow()==-1)
                    return;
                
                jTextField5.setText(df.format(listaArticulosP.get(jTable2.getSelectedRow()).getPrecioVenta2()));
                jTextField6.setText(df.format(listaArticulosP.get(jTable2.getSelectedRow()).getPrecioCompra()));
            }
        
        });
    }
    
    
}