package com.paedeias.identidades;
// Generated 26/03/2012 03:02:47 PM by Hibernate Tools 3.2.1.GA



/**
 * Articuloubicacion generated by hbm2java
 */
public class Articuloubicacion  implements java.io.Serializable {


     private Long id;
     private long idarticulo;
     private long idubicacion;
     private String ubicacion;

    public Articuloubicacion() {
    }

    public Articuloubicacion(long idarticulo, long idubicacion) {
       this.idarticulo = idarticulo;
       this.idubicacion = idubicacion;
    }

    public Articuloubicacion(long id, long idarticulo, long idubicacion) {
       this.id = id;
       this.idarticulo = idarticulo;
       this.idubicacion = idubicacion;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public long getIdarticulo() {
        return this.idarticulo;
    }
    
    public void setIdarticulo(long idarticulo) {
        this.idarticulo = idarticulo;
    }
    public long getIdubicacion() {
        return this.idubicacion;
    }
    
    public void setIdubicacion(long idubicacion) {
        this.idubicacion = idubicacion;
    }




}


