package com.paedeias.identidades;
// Generated 30-may-2012 11:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Cuentasporcobrar generated by hbm2java
 */
public class Cuentasporcobrar  implements java.io.Serializable {


     private Long id;
     private String venta;
     private String fechaVencimiento;
     private Integer pagado;
     private String observacion;
     private Double saldo;
     private String tipo;
     private Long cliente;
     private Long factura;
     
     private String fechaVenta;
     private String fechaLiquidacion;
     private String nombreCliente;
     private int diasCreditoCliente;

    public Cuentasporcobrar() {
    }

    public Cuentasporcobrar(String venta, String fechaVencimiento, Integer pagado, String observacion, Double saldo, String tipo) {
       this.venta = venta;
       this.fechaVencimiento = fechaVencimiento;
       this.pagado = pagado;
       this.observacion = observacion;
       this.saldo = saldo;
       this.tipo = tipo;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getVenta() {
        return this.venta;
    }
    
    public void setVenta(String venta) {
        this.venta = venta;
    }
    public String getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(String fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public Integer getPagado() {
        return this.pagado;
    }
    
    public void setPagado(Integer pagado) {
        this.pagado = pagado;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Double saldo) {
        this.saldo = saldo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Long getCliente() {
        return cliente;
    }

    public void setCliente(Long cliente) {
        this.cliente = cliente;
    }

    public Long getFactura() {
        return factura;
    }

    public void setFactura(Long factura) {
        this.factura = factura;
    }

    public int getDiasCreditoCliente() {
        return diasCreditoCliente;
    }

    public void setDiasCreditoCliente(int diasCreditoCliente) {
        this.diasCreditoCliente = diasCreditoCliente;
    }

    public String getFechaLiquidacion() {
        return fechaLiquidacion;
    }

    public void setFechaLiquidacion(String fechaLiquidacion) {
        this.fechaLiquidacion = fechaLiquidacion;
    }

    public String getFechaVenta() {
        return fechaVenta;
    }

    public void setFechaVenta(String fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    public String getNombreCliente() {
        return nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }




}


