package com.paedeias.identidades;
// Generated 12/03/2012 03:40:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Emisor generated by hbm2java
 */
public class Emisor  implements java.io.Serializable {


     private long idEmisor;
     private String emisor;
     private String rfc;
     private String emisorCalle;
     private String emisorCp;
     private String emisorColonia;
     private String emisorEstado;
     private String emisorLocalidad;
     private String emisorMunicipio;
     private String emisorNoExterior;
     private String emisorNoInterior;
     private String emisorPais;

    public Emisor() {
    }

    public Emisor(String emisor, String rfc, String emisorCalle, String emisorCp, String emisorColonia, String emisorEstado, String emisorLocalidad, String emisorMunicipio, String emisorNoExterior, String emisorNoInterior, String emisorPais) {
       this.emisor = emisor;
       this.rfc = rfc;
       this.emisorCalle = emisorCalle;
       this.emisorCp = emisorCp;
       this.emisorColonia = emisorColonia;
       this.emisorEstado = emisorEstado;
       this.emisorLocalidad = emisorLocalidad;
       this.emisorMunicipio = emisorMunicipio;
       this.emisorNoExterior = emisorNoExterior;
       this.emisorNoInterior = emisorNoInterior;
       this.emisorPais = emisorPais;
    }
   
    public long getIdEmisor() {
        return this.idEmisor;
    }
    
    public void setIdEmisor(long idEmisor) {
        this.idEmisor = idEmisor;
    }
    public String getEmisor() {
        return this.emisor;
    }
    
    public void setEmisor(String emisor) {
        this.emisor = emisor;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getEmisorCalle() {
        return this.emisorCalle;
    }
    
    public void setEmisorCalle(String emisorCalle) {
        this.emisorCalle = emisorCalle;
    }
    public String getEmisorCp() {
        return this.emisorCp;
    }
    
    public void setEmisorCp(String emisorCp) {
        this.emisorCp = emisorCp;
    }
    public String getEmisorColonia() {
        return this.emisorColonia;
    }
    
    public void setEmisorColonia(String emisorColonia) {
        this.emisorColonia = emisorColonia;
    }
    public String getEmisorEstado() {
        return this.emisorEstado;
    }
    
    public void setEmisorEstado(String emisorEstado) {
        this.emisorEstado = emisorEstado;
    }
    public String getEmisorLocalidad() {
        return this.emisorLocalidad;
    }
    
    public void setEmisorLocalidad(String emisorLocalidad) {
        this.emisorLocalidad = emisorLocalidad;
    }
    public String getEmisorMunicipio() {
        return this.emisorMunicipio;
    }
    
    public void setEmisorMunicipio(String emisorMunicipio) {
        this.emisorMunicipio = emisorMunicipio;
    }
    public String getEmisorNoExterior() {
        return this.emisorNoExterior;
    }
    
    public void setEmisorNoExterior(String emisorNoExterior) {
        this.emisorNoExterior = emisorNoExterior;
    }
    public String getEmisorNoInterior() {
        return this.emisorNoInterior;
    }
    
    public void setEmisorNoInterior(String emisorNoInterior) {
        this.emisorNoInterior = emisorNoInterior;
    }
    public String getEmisorPais() {
        return this.emisorPais;
    }
    
    public void setEmisorPais(String emisorPais) {
        this.emisorPais = emisorPais;
    }




}


