package com.paedeias.identidades;
// Generated 30-may-2012 11:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Partidasctasporpagar generated by hbm2java
 */
public class Partidasctasporpagar  implements java.io.Serializable {


     private Long id;
     private Long cuentaPorPagar;
     private Long compra;
     private Double importe;
     private String fecha;
     private String tipoPago;
     private String cheque;
     private String banco;
     private String observaciones;

    public Partidasctasporpagar() {
    }

    public Partidasctasporpagar(Long cuentaPorPagar, Long compra, Double importe, String fecha, String tipoPago, String cheque, String banco, String observaciones) {
       this.cuentaPorPagar = cuentaPorPagar;
       this.compra = compra;
       this.importe = importe;
       this.fecha = fecha;
       this.tipoPago = tipoPago;
       this.cheque = cheque;
       this.banco = banco;
       this.observaciones = observaciones;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getCuentaPorPagar() {
        return this.cuentaPorPagar;
    }
    
    public void setCuentaPorPagar(Long cuentaPorPagar) {
        this.cuentaPorPagar = cuentaPorPagar;
    }
    public Long getCompra() {
        return this.compra;
    }
    
    public void setCompra(Long compra) {
        this.compra = compra;
    }
    public Double getImporte() {
        return this.importe;
    }
    
    public void setImporte(Double importe) {
        this.importe = importe;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(String tipoPago) {
        this.tipoPago = tipoPago;
    }
    public String getCheque() {
        return this.cheque;
    }
    
    public void setCheque(String cheque) {
        this.cheque = cheque;
    }
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


