package com.paedeias.identidades;
// Generated 30-may-2012 11:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Long id;
     private Long idArticulo;
     private String codigoArticulo;
     private String descripcion;
     private Double costo;
     private Integer cantidad;
     private String fechaIni;
     private String fechaFin;
     private Long proveedor;
     private Integer surtido;
     private String de;
     private Long referencia;
     private Double precio;

    public Pedidos() {
    }

    public Pedidos(Long idArticulo, String codigoArticulo, String descripcion, Double costo, Integer cantidad, String fechaIni, String fechaFin, Long proveedor, Integer surtido, String de, Long referencia, Double precio) {
       this.idArticulo = idArticulo;
       this.codigoArticulo = codigoArticulo;
       this.descripcion = descripcion;
       this.costo = costo;
       this.cantidad = cantidad;
       this.fechaIni = fechaIni;
       this.fechaFin = fechaFin;
       this.proveedor = proveedor;
       this.surtido = surtido;
       this.de = de;
       this.referencia = referencia;
       this.precio = precio;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Long idArticulo) {
        this.idArticulo = idArticulo;
    }
    public String getCodigoArticulo() {
        return this.codigoArticulo;
    }
    
    public void setCodigoArticulo(String codigoArticulo) {
        this.codigoArticulo = codigoArticulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(String fechaIni) {
        this.fechaIni = fechaIni;
    }
    public String getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Long getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Long proveedor) {
        this.proveedor = proveedor;
    }
    public Integer getSurtido() {
        return this.surtido;
    }
    
    public void setSurtido(Integer surtido) {
        this.surtido = surtido;
    }
    public String getDe() {
        return this.de;
    }
    
    public void setDe(String de) {
        this.de = de;
    }
    public Long getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(Long referencia) {
        this.referencia = referencia;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


