package com.paedeias.identidades;
// Generated 30-may-2012 11:23:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pedidosventas generated by hbm2java
 */
public class Pedidosventas  implements java.io.Serializable {


     private Long id;
     private Long venta;
     private String codigoArticulo;
     private Integer cantidad;
     private Double precioUnitario;
     private Long vendedor;
     private String fecha;

    public Pedidosventas() {
    }

    public Pedidosventas(Long venta, String codigoArticulo, Integer cantidad, Double precioUnitario, Long vendedor, String fecha) {
       this.venta = venta;
       this.codigoArticulo = codigoArticulo;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.vendedor = vendedor;
       this.fecha = fecha;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getVenta() {
        return this.venta;
    }
    
    public void setVenta(Long venta) {
        this.venta = venta;
    }
    public String getCodigoArticulo() {
        return this.codigoArticulo;
    }
    
    public void setCodigoArticulo(String codigoArticulo) {
        this.codigoArticulo = codigoArticulo;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Long getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Long vendedor) {
        this.vendedor = vendedor;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


