package com.paedeias.identidades;
// Generated 12/03/2012 03:40:53 PM by Hibernate Tools 3.2.1.GA



/**
 * Receptor generated by hbm2java
 */
public class Receptor  implements java.io.Serializable {


     private long idReceptor;
     private String receptor;
     private String receptorRfc;
     private String receptorCalle;
     private String receptorCp;
     private String receptorColonia;
     private String receptorEstado;
     private String receptorLocalidad;
     private String receptorMunicipio;
     private String receptorNoExterior;
     private String receptorNoInterior;
     private String receptorPais;

    public Receptor() {
    }

    public Receptor(String receptor, String receptorRfc, String receptorCalle, String receptorCp, String receptorColonia, String receptorEstado, String receptorLocalidad, String receptorMunicipio, String receptorNoExterior, String receptorNoInterior, String receptorPais) {
       this.receptor = receptor;
       this.receptorRfc = receptorRfc;
       this.receptorCalle = receptorCalle;
       this.receptorCp = receptorCp;
       this.receptorColonia = receptorColonia;
       this.receptorEstado = receptorEstado;
       this.receptorLocalidad = receptorLocalidad;
       this.receptorMunicipio = receptorMunicipio;
       this.receptorNoExterior = receptorNoExterior;
       this.receptorNoInterior = receptorNoInterior;
       this.receptorPais = receptorPais;
    }
   
    public long getIdReceptor() {
        return this.idReceptor;
    }
    
    public void setIdReceptor(long idReceptor) {
        this.idReceptor = idReceptor;
    }
    public String getReceptor() {
        return this.receptor;
    }
    
    public void setReceptor(String receptor) {
        this.receptor = receptor;
    }
    public String getReceptorRfc() {
        return this.receptorRfc;
    }
    
    public void setReceptorRfc(String receptorRfc) {
        this.receptorRfc = receptorRfc;
    }
    public String getReceptorCalle() {
        return this.receptorCalle;
    }
    
    public void setReceptorCalle(String receptorCalle) {
        this.receptorCalle = receptorCalle;
    }
    public String getReceptorCp() {
        return this.receptorCp;
    }
    
    public void setReceptorCp(String receptorCp) {
        this.receptorCp = receptorCp;
    }
    public String getReceptorColonia() {
        return this.receptorColonia;
    }
    
    public void setReceptorColonia(String receptorColonia) {
        this.receptorColonia = receptorColonia;
    }
    public String getReceptorEstado() {
        return this.receptorEstado;
    }
    
    public void setReceptorEstado(String receptorEstado) {
        this.receptorEstado = receptorEstado;
    }
    public String getReceptorLocalidad() {
        return this.receptorLocalidad;
    }
    
    public void setReceptorLocalidad(String receptorLocalidad) {
        this.receptorLocalidad = receptorLocalidad;
    }
    public String getReceptorMunicipio() {
        return this.receptorMunicipio;
    }
    
    public void setReceptorMunicipio(String receptorMunicipio) {
        this.receptorMunicipio = receptorMunicipio;
    }
    public String getReceptorNoExterior() {
        return this.receptorNoExterior;
    }
    
    public void setReceptorNoExterior(String receptorNoExterior) {
        this.receptorNoExterior = receptorNoExterior;
    }
    public String getReceptorNoInterior() {
        return this.receptorNoInterior;
    }
    
    public void setReceptorNoInterior(String receptorNoInterior) {
        this.receptorNoInterior = receptorNoInterior;
    }
    public String getReceptorPais() {
        return this.receptorPais;
    }
    
    public void setReceptorPais(String receptorPais) {
        this.receptorPais = receptorPais;
    }




}


